# Generated by Django 5.0.1 on 2025-12-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adressen_type', models.CharField(choices=[('Adresse', 'Adresse'), ('KUNDE', 'Kunde'), ('LIEFERANT', 'Lieferant'), ('STANDORT', 'Standort'), ('SONSTIGES', 'Sonstiges')], default='Adresse', max_length=20)),
                ('firma', models.CharField(blank=True, max_length=100, null=True)),
                ('anrede', models.CharField(blank=True, choices=[('HERR', 'Herr'), ('FRAU', 'Frau'), ('DIVERS', 'Divers')], max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('strasse', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=50, null=True)),
                ('mobil', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
