# Generated by Django 5.2.9 on 2025-12-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Template Key')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('message_html', models.TextField(verbose_name='HTML Nachricht')),
                ('from_address', models.EmailField(max_length=254, verbose_name='Von E-Mail')),
                ('from_name', models.CharField(max_length=255, verbose_name='Von Name')),
                ('cc_copy_to', models.EmailField(blank=True, max_length=254, verbose_name='CC Kopie an')),
            ],
            options={
                'verbose_name': 'E-Mail Template',
                'verbose_name_plural': 'E-Mail Templates',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SmtpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='SMTP Host')),
                ('port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Use STARTTLS')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'SMTP Einstellungen',
                'verbose_name_plural': 'SMTP Einstellungen',
            },
        ),
    ]
