# Generated by Django 5.2.9 on 2025-12-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mailtemplate_smtpsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('adresse', models.CharField(max_length=200, verbose_name='Adresse')),
                ('plz', models.CharField(max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(max_length=100, verbose_name='Ort')),
                ('land', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('internet', models.URLField(blank=True, verbose_name='Internet')),
                ('steuernummer', models.CharField(blank=True, max_length=50, verbose_name='Steuernummer')),
                ('ust_id_nr', models.CharField(blank=True, max_length=50, verbose_name='UStIdNr')),
                ('geschaeftsfuehrer', models.CharField(blank=True, max_length=200, verbose_name='Geschäftsführer')),
                ('kreditinstitut', models.CharField(blank=True, max_length=200, verbose_name='Kreditinstitut')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('kontoinhaber', models.CharField(blank=True, max_length=200, verbose_name='Kontoinhaber')),
            ],
            options={
                'verbose_name': 'Mandant',
                'verbose_name_plural': 'Mandanten',
                'ordering': ['name'],
            },
        ),
    ]
