# Generated by Django 5.2.10 on 2026-01-22 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mandant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kostenart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.kostenart', verbose_name='Hauptkostenart')),
            ],
            options={
                'verbose_name': 'Kostenart',
                'verbose_name_plural': 'Kostenarten',
                'ordering': ['name'],
            },
        ),
    ]
