# Generated by Django 5.2.10 on 2026-01-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kostenart'),
    ]

    operations = [
        migrations.AddField(
            model_name='kostenart',
            name='umsatzsteuer_satz',
            field=models.CharField(choices=[('0', '0% Umsatzsteuer (steuerfrei)'), ('7', '7% Umsatzsteuer (ermäßigt)'), ('19', '19% Umsatzsteuer (regulär)')], default='19', max_length=2, verbose_name='Umsatzsteuer-Satz'),
        ),
    ]
