# Generated by Django 5.2.10 on 2026-01-31 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_activity_reminder_mail_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('provider_type', models.CharField(choices=[('OpenAI', 'OpenAI'), ('Gemini', 'Gemini'), ('Claude', 'Claude')], max_length=20, verbose_name='Provider Type')),
                ('api_key', models.CharField(help_text='Encrypted API key for the provider', max_length=500, verbose_name='API Key')),
                ('organization_id', models.CharField(blank=True, help_text='Optional organization ID (e.g., for OpenAI)', max_length=200, verbose_name='Organization ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['provider_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('model_id', models.CharField(help_text='Provider-specific model identifier (e.g., gpt-4, gemini-pro)', max_length=100, verbose_name='Model ID')),
                ('input_price_per_1m_tokens', models.DecimalField(decimal_places=4, default=0, help_text='Price in USD per 1 million input tokens', max_digits=10, verbose_name='Input Price per 1M Tokens')),
                ('output_price_per_1m_tokens', models.DecimalField(decimal_places=4, default=0, help_text='Price in USD per 1 million output tokens', max_digits=10, verbose_name='Output Price per 1M Tokens')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.aiprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['provider', 'name'],
                'unique_together': {('provider', 'model_id')},
            },
        ),
        migrations.CreateModel(
            name='AIJobsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(help_text="Agent or service that initiated the call (e.g., 'core.ai', 'manual')", max_length=100, verbose_name='Agent')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Error', 'Error')], default='Pending', max_length=20, verbose_name='Status')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP')),
                ('input_tokens', models.IntegerField(blank=True, null=True, verbose_name='Input Tokens')),
                ('output_tokens', models.IntegerField(blank=True, null=True, verbose_name='Output Tokens')),
                ('costs', models.DecimalField(blank=True, decimal_places=6, help_text='Calculated cost in USD', max_digits=10, null=True, verbose_name='Costs (USD)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('duration_ms', models.IntegerField(blank=True, help_text='API call duration in milliseconds', null=True, verbose_name='Duration (ms)')),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is Error', verbose_name='Error Message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.aimodel', verbose_name='Model')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.aiprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'AI Job History',
                'verbose_name_plural': 'AI Jobs History',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_aijobs_timesta_1f459d_idx'), models.Index(fields=['status'], name='core_aijobs_status_7be391_idx'), models.Index(fields=['provider'], name='core_aijobs_provide_5cd2ee_idx'), models.Index(fields=['model'], name='core_aijobs_model_i_45a0c6_idx')],
            },
        ),
    ]
