# Generated by Django 6.0.1 on 2026-01-31 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aiprovider_aimodel_aijobshistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(help_text="Report type identifier (e.g., 'change.v1', 'invoice.v1')", max_length=100, verbose_name='Report Key')),
                ('object_type', models.CharField(help_text="Type of the related object (e.g., 'change', 'invoice')", max_length=100, verbose_name='Object Type')),
                ('object_id', models.CharField(help_text='ID of the related object', max_length=100, verbose_name='Object ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('context_json', models.JSONField(help_text='JSON snapshot of the data used to generate the report', verbose_name='Context Snapshot')),
                ('pdf_file', models.FileField(upload_to='reports/%Y/%m/%d/', verbose_name='PDF File')),
                ('template_version', models.CharField(blank=True, help_text='Version or hash of the template used', max_length=50, verbose_name='Template Version')),
                ('sha256', models.CharField(blank=True, help_text='SHA256 hash of the PDF for integrity verification', max_length=64, verbose_name='SHA256 Hash')),
                ('metadata', models.JSONField(blank=True, help_text='Optional additional metadata', null=True, verbose_name='Additional Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Report Document',
                'verbose_name_plural': 'Report Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_key', '-created_at'], name='core_report_report__bd323f_idx'), models.Index(fields=['object_type', 'object_id', '-created_at'], name='core_report_object__445e1d_idx')],
            },
        ),
    ]
