# Generated by Django 5.2.10 on 2026-02-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reportdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseKontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TELEFON', 'Telefon'), ('MOBIL', 'Mobil'), ('TELEFAX', 'Telefax'), ('EMAIL', 'E-Mail')], max_length=20, verbose_name='Kontakttyp')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('kontakt', models.CharField(max_length=200, verbose_name='Kontakt')),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontakte', to='core.adresse', verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Adresse Kontakt',
                'verbose_name_plural': 'Adresse Kontakte',
                'ordering': ['type', 'name'],
                'indexes': [models.Index(fields=['adresse'], name='core_adress_adresse_10e7cb_idx'), models.Index(fields=['adresse', 'type'], name='core_adress_adresse_ce6925_idx')],
            },
        ),
    ]
