# Generated by Django 5.2.11 on 2026-02-06 08:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_adresse_kontakt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Eindeutiger Code für den Steuersatz (z.B. VAT, REDUCED)', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Bezeichnung des Steuersatzes', max_length=200, verbose_name='Name')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Steuersatz als Dezimalzahl (z.B. 0.19 für 19%)', max_digits=5, verbose_name='Steuersatz')),
                ('is_active', models.BooleanField(default=True, help_text='Gibt an, ob dieser Steuersatz aktiv ist', verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Steuersatz',
                'verbose_name_plural': 'Steuersätze',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='taxrate_code_unique_case_insensitive', violation_error_message='Ein Steuersatz mit diesem Code existiert bereits (Groß-/Kleinschreibung wird ignoriert).')],
            },
        ),
    ]
