# Generated by Django 5.2.11 on 2026-02-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_taxrate_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Bezeichnung der Zahlungsbedingung (z.B. '2% Skonto 10 Tage, netto 30 Tage')", max_length=200, verbose_name='Name')),
                ('discount_days', models.IntegerField(blank=True, help_text='Anzahl Tage für Skontoabzug (optional)', null=True, verbose_name='Skontofrist (Tage)')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Skontosatz als Dezimalzahl (z.B. 0.02 für 2%)', max_digits=5, null=True, verbose_name='Skontosatz')),
                ('net_days', models.IntegerField(help_text='Anzahl Tage bis zur Fälligkeit (Netto)', verbose_name='Zahlungsziel (Tage)')),
                ('is_default', models.BooleanField(default=False, help_text='Ist dies die Standard-Zahlungsbedingung für diesen Mandanten?', verbose_name='Standard')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_terms', to='core.mandant', verbose_name='Mandant')),
            ],
            options={
                'verbose_name': 'Zahlungsbedingung',
                'verbose_name_plural': 'Zahlungsbedingungen',
                'ordering': ['company', 'name'],
                'indexes': [models.Index(fields=['company'], name='core_paymen_company_0e219b_idx'), models.Index(fields=['company', 'is_default'], name='core_paymen_company_dece61_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='unique_default_payment_term_per_company', violation_error_message='Es kann nur eine Standard-Zahlungsbedingung pro Mandant existieren.')],
            },
        ),
    ]
