# Generated by Django 5.2.9 on 2026-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_paymentterm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentterm',
            options={'ordering': ['name'], 'verbose_name': 'Zahlungsbedingung', 'verbose_name_plural': 'Zahlungsbedingungen'},
        ),
        migrations.RemoveConstraint(
            model_name='paymentterm',
            name='unique_default_payment_term_per_company',
        ),
        migrations.RemoveIndex(
            model_name='paymentterm',
            name='core_paymen_company_0e219b_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentterm',
            name='core_paymen_company_dece61_idx',
        ),
        migrations.RemoveField(
            model_name='paymentterm',
            name='company',
        ),
        migrations.AddIndex(
            model_name='paymentterm',
            index=models.Index(fields=['is_default'], name='core_paymen_is_defa_bbf9b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentterm',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_payment_term', violation_error_message='Es kann nur eine Standard-Zahlungsbedingung existieren.'),
        ),
    ]
