# Generated by Django 5.2.11 on 2026-02-06 10:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_paymentterm_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bezeichnung des Artikels/der Leistung', max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Detaillierte Beschreibung', verbose_name='Beschreibung')),
                ('unit_price_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standardpreis netto', max_digits=12, verbose_name='Netto-Stückpreis')),
                ('is_active', models.BooleanField(default=True, help_text='Gibt an, ob dieser Artikel aktiv ist', verbose_name='Aktiv')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.taxrate', verbose_name='Steuersatz')),
            ],
            options={
                'verbose_name': 'Artikel/Leistung',
                'verbose_name_plural': 'Artikel/Leistungen',
                'ordering': ['name'],
            },
        ),
    ]
