# Generated by Django 5.2.11 on 2026-02-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='country_code',
            field=models.CharField(blank=True, default='DE', help_text='ISO 3166-1 Alpha-2 Ländercode (z.B. DE, AT, FR)', max_length=2, verbose_name='Ländercode'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='debitor_number',
            field=models.CharField(blank=True, help_text='Debitorennummer für die Buchhaltung (optional)', max_length=32, null=True, verbose_name='Debitorennummer'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='is_business',
            field=models.BooleanField(default=True, help_text='Ist dies ein Unternehmer/Geschäftskunde?', verbose_name='Unternehmer'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='is_eu',
            field=models.BooleanField(default=False, help_text='Ist dies ein EU-Kunde?', verbose_name='EU'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='vat_id',
            field=models.CharField(blank=True, help_text='Umsatzsteuer-Identifikationsnummer (optional)', max_length=32, null=True, verbose_name='USt-IdNr.'),
        ),
    ]
