# Generated by Django 5.2.11 on 2026-02-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_extend_item_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='item',
            new_name='core_item_article_e3fd5c_idx',
            old_name='core_item_article_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='core_item_is_acti_8c2f25_idx',
            old_name='core_item_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='core_item_item_ty_e3aaee_idx',
            old_name='core_item_item_type_idx',
        ),
    ]
