# Generated by Django 5.2.11 on 2026-02-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_core_item_article_idx_core_item_article_e3fd5c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Eindeutiger Code für die Warengruppe', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Bezeichnung der Warengruppe', max_length=200, verbose_name='Name')),
                ('group_type', models.CharField(choices=[('MAIN', 'Hauptwarengruppe'), ('SUB', 'Unterwarengruppe')], help_text='Typ der Warengruppe (Haupt- oder Untergruppe)', max_length=10, verbose_name='Gruppentyp')),
                ('is_active', models.BooleanField(default=True, help_text='Gibt an, ob diese Warengruppe aktiv ist', verbose_name='Aktiv')),
                ('description', models.TextField(blank=True, help_text='Optional: Beschreibung der Warengruppe', null=True, verbose_name='Beschreibung')),
                ('parent', models.ForeignKey(blank=True, help_text='Übergeordnete Hauptwarengruppe (nur bei Untergruppen)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.itemgroup', verbose_name='Hauptwarengruppe')),
            ],
            options={
                'verbose_name': 'Warengruppe',
                'verbose_name_plural': 'Warengruppen',
                'ordering': ['code'],
            },
        ),
    ]
