# Generated by Django 5.2.11 on 2026-02-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_itemgroup_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(blank=True, help_text='Optional: Zuordnung zu einer Unterwarengruppe (SUB)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.itemgroup', verbose_name='Warengruppe'),
        ),
    ]
