# Generated by Django 5.2.11 on 2026-02-06 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_item_group_to_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('RENTAL', 'Vermietung'), ('ORDER', 'Auftragsverwaltung'), ('FINANCE', 'Finanzen')], help_text='Fachlicher Bereich (Vermietung, Auftragsverwaltung, Finanzen)', max_length=20, verbose_name='Bereich')),
                ('activity_type', models.CharField(help_text='Maschinenlesbarer Code, z.B. INVOICE_CREATED, CONTRACT_RUN_FAILED', max_length=64, verbose_name='Aktivitätstyp')),
                ('title', models.CharField(help_text='Kurze Beschreibung der Aktivität', max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, help_text='Optionale detaillierte Beschreibung', null=True, verbose_name='Beschreibung')),
                ('target_url', models.CharField(help_text='Klickbarer Link zum betroffenen Objekt (relativ), z.B. /auftragsverwaltung/documents/123', max_length=500, verbose_name='Ziel-URL')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warnung'), ('ERROR', 'Fehler')], default='INFO', help_text='Schweregrad der Aktivität', max_length=10, verbose_name='Schweregrad')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('actor', models.ForeignKey(blank=True, help_text='Benutzer, der die Aktion ausgeführt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Akteur')),
                ('company', models.ForeignKey(help_text='Zugehöriger Mandant', on_delete=django.db.models.deletion.CASCADE, to='core.mandant', verbose_name='Mandant')),
            ],
            options={
                'verbose_name': 'Aktivität',
                'verbose_name_plural': 'Aktivitäten',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_created_at_idx'), models.Index(fields=['company', '-created_at'], name='activity_company_created_idx'), models.Index(fields=['company', 'domain', '-created_at'], name='activity_company_domain_idx')],
            },
        ),
    ]
