# Generated by Django 5.2.11 on 2026-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_activity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Eindeutiger Code für die Einheit (z.B. STK, PAU, LFM)', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Bezeichnung der Einheit (z.B. Stück, Pauschal, Laufender Meter)', max_length=200, verbose_name='Name')),
                ('symbol', models.CharField(blank=True, default='', help_text='Optionales Symbol für die Einheit (z.B. Stk, lfm)', max_length=50, verbose_name='Symbol')),
                ('is_active', models.BooleanField(default=True, help_text='Gibt an, ob diese Einheit aktiv ist', verbose_name='Aktiv')),
                ('description', models.TextField(blank=True, default='', help_text='Optionale Beschreibung der Einheit', verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unit_code_unique', violation_error_message='Eine Einheit mit diesem Code existiert bereits.')],
            },
        ),
    ]
