# Generated by Django 5.2.11 on 2026-02-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_unit_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandant',
            name='logo_path',
            field=models.CharField(blank=True, help_text='Relativer Pfad zum Logo im Media-Verzeichnis', max_length=255, verbose_name='Logo Pfad'),
        ),
    ]
