# Generated by Django 5.2.11 on 2026-02-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_mandant_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandant',
            name='handelsregister',
            field=models.CharField(blank=True, max_length=200, verbose_name='Handelsregister'),
        ),
    ]
