# Generated by Django 5.2.11 on 2026-02-24 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_handelsregister_to_mandant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text='Projektbezeichnung', max_length=255, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, default='', help_text='Beschreibung des Projekts', verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('NEU', 'Neu'), ('IN_BEARBEITUNG', 'In Bearbeitung'), ('WARTET', 'Wartet'), ('ZURUECKGESTELLT', 'Zurückgestellt'), ('ABGESCHLOSSEN', 'Abgeschlossen')], default='NEU', help_text='Aktueller Projektstatus', max_length=20, verbose_name='Status')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projekte', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='ProjektFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Dateiname / Ordnername')),
                ('ordner', models.CharField(blank=True, default='', help_text='Pfad des übergeordneten Ordners (leer = Projektwurzel)', max_length=500, verbose_name='Ordner')),
                ('is_folder', models.BooleanField(default=False, verbose_name='Ist Ordner')),
                ('storage_path', models.CharField(blank=True, default='', max_length=1000, verbose_name='Speicherpfad')),
                ('file_size', models.IntegerField(blank=True, help_text='Dateigröße in Bytes', null=True, verbose_name='Dateigröße')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME-Type')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projekt_files', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.projekt', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Projektdatei',
                'verbose_name_plural': 'Projektdateien',
                'ordering': ['-is_folder', 'ordner', 'filename'],
            },
        ),
    ]
