# Generated by Django 5.2.12 on 2026-03-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_fix_activity_description_html_rendering'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='invoice_email',
            field=models.EmailField(blank=True, help_text='E-Mail-Adresse für den Rechnungsversand', max_length=254, null=True, verbose_name='E-Mail Rechnung'),
        ),
    ]
