# Generated by Django 5.2.12 on 2026-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_invoice_sent_mail_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('SERVICE', 'Dienstleistung'), ('VERMIETUNG', 'Vermietung')], help_text='Klassifizierung: Material, Dienstleistung oder Vermietung', max_length=20, verbose_name='Artikeltyp'),
        ),
    ]
