# Generated by Django 5.2.12 on 2026-04-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='article_no',
            field=models.CharField(blank=True, help_text='Eindeutige Artikelnummer (global, wird automatisch vergeben)', max_length=100, null=True, unique=True, verbose_name='Artikelnummer'),
        ),
    ]
