# Generated by Django 5.2.12 on 2026-04-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_item_article_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adresse',
            constraint=models.UniqueConstraint(condition=models.Q(('debitor_number__isnull', False)), fields=('debitor_number',), name='unique_debitor_number', violation_error_message='Diese Debitorennummer ist bereits vergeben.'),
        ),
    ]
