# Generated by Django 5.2.16 on 2026-08-27 08:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_debitor_number_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='matchkey',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=models.Case(models.When(models.Q(('firma__isnull', False), models.Q(('firma', ''), _negated=True)), then=django.db.models.functions.text.Concat(models.F('firma'), models.Value(' ('), models.F('name'), models.Value(')'))), default=models.F('name'), output_field=models.CharField(max_length=210)), help_text='Ergibt sich automatisch aus Firma und Name: „Firma (Name)“ bzw. „Name“.', output_field=models.CharField(max_length=210), verbose_name='Matchkey'),
        ),
        migrations.AddIndex(
            model_name='adresse',
            index=models.Index(fields=['adressen_type', 'matchkey'], name='core_adresse_type_mk_idx'),
        ),
    ]
