# Generated by Django 5.2.16 on 2026-08-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_adresse_matchkey_adresse_core_adresse_type_mk_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Optionaler Mandant des Projekts', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projekte', to='core.mandant', verbose_name='Mandant'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='kunde',
            field=models.ForeignKey(blank=True, help_text='Optionaler Kunde des Projekts (leer = internes Projekt)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projekte', to='core.adresse', verbose_name='Kunde'),
        ),
    ]
