# Generated by Django 5.2.16 on 2026-08-29 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_projekt_company_projekt_kunde'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Optional: Standard-Mengeneinheit, die bei der Artikelauswahl in die Belegposition übernommen wird', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.unit', verbose_name='Mengeneinheit'),
        ),
    ]
