# Generated by Django 5.2.16 on 2026-08-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kostenart',
            name='aufwandskonto',
            field=models.CharField(blank=True, default='', help_text='Sachkonto für Eingangsrechnungen dieser Kostenart. Leer lassen, um das Konto der Hauptkostenart zu verwenden.', max_length=20, verbose_name='Aufwandskonto'),
        ),
        migrations.AddField(
            model_name='kostenart',
            name='erloeskonto',
            field=models.CharField(blank=True, default='', help_text='Optionales Erlöskonto. Ist es gesetzt, übersteuert es das Erlöskonto aus dem Steuersatz.', max_length=20, verbose_name='Erlöskonto'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='debitor_number',
            field=models.CharField(blank=True, help_text='Personenkonto für die Buchhaltung: Debitorenkonto bei Kunden, Kreditorenkonto bei Lieferanten. Wird bei der Neuanlage automatisch vergeben.', max_length=32, null=True, verbose_name='Debitoren-/Kreditorenkonto'),
        ),
    ]
