# Generated by Django 5.2.16 on 2026-08-30 13:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_datev_personenkonten'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='billing_item',
            field=models.ForeignKey(blank=True, help_text='Artikel für die Abrechnung der Leistungszeit. Liefert Kurztexte, Einheit, Steuersatz und Rabattfähigkeit der Rechnungsposition.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projekte_leistung', to='core.item', verbose_name='Abrechnungsartikel (Leistung)'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rabatt in Prozent (z.B. 10.00 für 10% Rabatt), wird in die Rechnungspositionen übernommen', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Rabatt (%)'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gilt für dieses Projekt und übersteuert den Preis aus dem Artikel.', max_digits=10, null=True, verbose_name='Stundensatz (netto)'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='travel_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gilt für dieses Projekt und übersteuert den Preis aus dem Anfahrtsartikel.', max_digits=10, null=True, verbose_name='Stundensatz Anfahrt (netto)'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='travel_item',
            field=models.ForeignKey(blank=True, help_text='Artikel für die Abrechnung der Anfahrtszeit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projekte_anfahrt', to='core.item', verbose_name='Abrechnungsartikel (Anfahrt)'),
        ),
    ]
