# Generated by Django 5.2.11 on 2026-02-06 22:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auftragsverwaltung', '0013_extend_numberrange_for_contracts'),
        ('core', '0022_add_activity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datev_consultant_number', models.CharField(blank=True, help_text='DATEV Beraternummer (mit führenden Nullen)', max_length=20, verbose_name='DATEV Beraternummer')),
                ('datev_client_number', models.CharField(blank=True, help_text='DATEV Mandantennummer (mit führenden Nullen)', max_length=20, verbose_name='DATEV Mandantennummer')),
                ('tax_number', models.CharField(blank=True, help_text='Steuernummer des Mandanten', max_length=50, verbose_name='Steuernummer')),
                ('revenue_account_0', models.CharField(blank=True, help_text='Erlöskonto für Steuersatz 0% (mit führenden Nullen)', max_length=20, verbose_name='Erlöskonto 0%')),
                ('revenue_account_7', models.CharField(blank=True, help_text='Erlöskonto für Steuersatz 7% (mit führenden Nullen)', max_length=20, verbose_name='Erlöskonto 7%')),
                ('revenue_account_19', models.CharField(blank=True, help_text='Erlöskonto für Steuersatz 19% (mit führenden Nullen)', max_length=20, verbose_name='Erlöskonto 19%')),
                ('company', models.OneToOneField(help_text='Mandant für diese Buchhaltungseinstellungen', on_delete=django.db.models.deletion.PROTECT, related_name='accounting_settings', to='core.mandant', verbose_name='Mandant')),
            ],
            options={
                'verbose_name': 'Buchhaltungseinstellungen',
                'verbose_name_plural': 'Buchhaltungseinstellungen',
            },
        ),
        migrations.CreateModel(
            name='OutgoingInvoiceJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(help_text='Snapshot: Belegnummer zum Zeitpunkt der Journal-Erzeugung', max_length=32, verbose_name='Belegnummer')),
                ('document_date', models.DateField(help_text='Snapshot: Belegdatum', verbose_name='Belegdatum')),
                ('document_kind', models.CharField(choices=[('INVOICE', 'Rechnung'), ('CREDIT_NOTE', 'Gutschrift')], help_text='Rechnung oder Gutschrift', max_length=20, verbose_name='Belegart')),
                ('customer_name', models.CharField(help_text='Snapshot: Kundenname', max_length=200, verbose_name='Kundenname')),
                ('debtor_number', models.CharField(blank=True, help_text='Snapshot: Debitorennummer (optional)', max_length=32, verbose_name='Debitorennummer')),
                ('net_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Nettobetrag mit Steuersatz 0%', max_digits=10, verbose_name='Netto 0%')),
                ('net_7', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Nettobetrag mit Steuersatz 7%', max_digits=10, verbose_name='Netto 7%')),
                ('net_19', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Nettobetrag mit Steuersatz 19%', max_digits=10, verbose_name='Netto 19%')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gesamter Steuerbetrag', max_digits=10, verbose_name='Steuerbetrag')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gesamtbetrag brutto', max_digits=10, verbose_name='Bruttobetrag')),
                ('revenue_account_0', models.CharField(blank=True, help_text='Snapshot: Erlöskonto für Steuersatz 0%', max_length=20, verbose_name='Erlöskonto 0%')),
                ('revenue_account_7', models.CharField(blank=True, help_text='Snapshot: Erlöskonto für Steuersatz 7%', max_length=20, verbose_name='Erlöskonto 7%')),
                ('revenue_account_19', models.CharField(blank=True, help_text='Snapshot: Erlöskonto für Steuersatz 19%', max_length=20, verbose_name='Erlöskonto 19%')),
                ('export_status', models.CharField(choices=[('OPEN', 'Offen'), ('EXPORTED', 'Exportiert'), ('ERROR', 'Fehler')], default='OPEN', help_text='Status des DATEV-Exports', max_length=20, verbose_name='Export-Status')),
                ('exported_at', models.DateTimeField(blank=True, help_text='Zeitpunkt des letzten erfolgreichen Exports', null=True, verbose_name='Exportiert am')),
                ('export_batch_id', models.CharField(blank=True, help_text='ID der Export-Charge (optional)', max_length=100, verbose_name='Export-Batch-ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Journal-Eintrag-Erzeugung', verbose_name='Erstellt am')),
                ('company', models.ForeignKey(help_text='Mandant für diesen Journal-Eintrag', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='core.mandant', verbose_name='Mandant')),
                ('document', models.ForeignKey(help_text='Referenziertes Verkaufsdokument', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='auftragsverwaltung.salesdocument', verbose_name='Dokument')),
            ],
            options={
                'verbose_name': 'Rechnungsausgangsjournal-Eintrag',
                'verbose_name_plural': 'Rechnungsausgangsjournal-Einträge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'document_date'], name='finanzen_ou_company_88fb0c_idx'), models.Index(fields=['company', 'export_status'], name='finanzen_ou_company_785c24_idx'), models.Index(fields=['document_number'], name='finanzen_ou_documen_67f023_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'document'), name='unique_journal_entry_per_company_document', violation_error_message='Es kann nur einen Journal-Eintrag pro Mandant und Dokument geben.'), models.UniqueConstraint(fields=('company', 'document_number'), name='unique_document_number_per_company', violation_error_message='Die Belegnummer muss pro Mandant eindeutig sein.')],
            },
        ),
    ]
