# Generated by Django 5.2.16 on 2026-08-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoinginvoicejournalentry',
            name='customer_name',
            field=models.CharField(help_text='Snapshot: Matchkey des Kunden („Firma (Name)“ bzw. „Name“)', max_length=200, verbose_name='Kundenname'),
        ),
    ]
