# Generated by Django 5.2.16 on 2026-08-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzen', '0002_alter_outgoinginvoicejournalentry_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='account_length',
            field=models.PositiveSmallIntegerField(default=4, help_text='Stellenanzahl der Sachkonten im Kontenrahmen (Standard 4). Personenkonten sind eine Stelle länger.', verbose_name='Sachkontenlänge'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='bank_account',
            field=models.CharField(blank=True, default='', help_text='Sachkonto der Bank (mit führenden Nullen)', max_length=20, verbose_name='Gegenkonto Bank'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='cash_account',
            field=models.CharField(blank=True, default='', help_text='Sachkonto der Kasse (mit führenden Nullen)', max_length=20, verbose_name='Gegenkonto Kasse'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='clearing_account',
            field=models.CharField(blank=True, default='', help_text='Sachkonto für Verrechnungen (mit führenden Nullen)', max_length=20, verbose_name='Verrechnungskonto'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='fiscal_year_start',
            field=models.DateField(blank=True, help_text='Erster Tag des Wirtschaftsjahres. Leer lassen für den 1. Januar des Exportjahres (Kalenderwirtschaftsjahr).', null=True, verbose_name='Wirtschaftsjahresbeginn'),
        ),
        migrations.AlterField(
            model_name='companyaccountingsettings',
            name='datev_client_number',
            field=models.CharField(blank=True, default='1', help_text='Pflichtfeld des EXTF-Kopfsatzes. Platzhalter 1 genügt, solange nicht an einen Steuerberater übermittelt wird (mit führenden Nullen).', max_length=20, verbose_name='DATEV Mandantennummer'),
        ),
        migrations.AlterField(
            model_name='companyaccountingsettings',
            name='datev_consultant_number',
            field=models.CharField(blank=True, default='1001', help_text='Pflichtfeld des EXTF-Kopfsatzes. Solange nicht an einen Steuerberater übermittelt wird, genügt der Platzhalter 1001; für die Übermittlung die echte Beraternummer eintragen (mit führenden Nullen).', max_length=20, verbose_name='DATEV Beraternummer'),
        ),
    ]
