# Generated by Django 5.2.11 on 2026-02-06 08:27

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Eindeutiger maschinenlesbarer Schlüssel (z.B. 'rechnung', 'angebot')", max_length=50, unique=True, verbose_name='Key')),
                ('name', models.CharField(help_text='Menschenlesbare Bezeichnung des Dokumenttyps', max_length=200, verbose_name='Name')),
                ('prefix', models.CharField(help_text="Präfix für Nummerierung (z.B. 'R', 'A', 'AB')", max_length=10, verbose_name='Präfix')),
                ('is_invoice', models.BooleanField(default=False, help_text='Kennzeichnet, ob dieser Dokumenttyp eine Rechnung ist', verbose_name='Ist Rechnung')),
                ('is_correction', models.BooleanField(default=False, help_text='Kennzeichnet, ob dieser Dokumenttyp eine Korrektur ist', verbose_name='Ist Korrektur')),
                ('requires_due_date', models.BooleanField(default=False, help_text='Kennzeichnet, ob ein Fälligkeitsdatum erforderlich ist', verbose_name='Fälligkeitsdatum erforderlich')),
                ('is_active', models.BooleanField(default=True, help_text='Gibt an, ob dieser Dokumenttyp aktiv ist', verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Dokumenttyp',
                'verbose_name_plural': 'Dokumenttypen',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='doctype_key_idx'), models.Index(fields=['is_active'], name='doctype_is_active_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('key'), name='documenttype_key_unique_case_insensitive', violation_error_message='Ein Dokumenttyp mit diesem Key existiert bereits (Groß-/Kleinschreibung wird ignoriert).')],
            },
        ),
    ]
