# Generated by Django 5.2.11 on 2026-02-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documenttype',
            name='doctype_key_idx',
        ),
    ]
