# Generated by Django 5.2.11 on 2026-02-06 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0002_remove_documenttype_doctype_key_idx'),
        ('core', '0014_paymentterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(default='{prefix}{yy}-{seq:05d}', help_text='Format string with tokens: {prefix}, {yy}, {seq:05d}', max_length=100, verbose_name='Format')),
                ('reset_policy', models.CharField(choices=[('YEARLY', 'Yearly Reset'), ('NEVER', 'Never Reset')], default='YEARLY', help_text='YEARLY: Reset sequence on year change, NEVER: Continuous sequence', max_length=10, verbose_name='Reset-Policy')),
                ('current_year', models.IntegerField(default=0, help_text='Zweistellige Jahreszahl der zuletzt vergebenen Nummer', verbose_name='Aktuelles Jahr (YY)')),
                ('current_seq', models.IntegerField(default=0, help_text='Zuletzt vergebene Sequenznummer', verbose_name='Aktuelle Sequenz')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_ranges', to='core.mandant', verbose_name='Mandant')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_ranges', to='auftragsverwaltung.documenttype', verbose_name='Dokumenttyp')),
            ],
            options={
                'verbose_name': 'Nummernkreis',
                'verbose_name_plural': 'Nummernkreise',
                'ordering': ['company', 'document_type'],
                'indexes': [models.Index(fields=['company', 'document_type'], name='auftragsver_company_e81275_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type'), name='unique_numberrange_per_company_doctype', violation_error_message='Es kann nur einen Nummernkreis pro Mandant und Dokumenttyp geben.')],
            },
        ),
    ]
