# Generated by Django 5.2.11 on 2026-02-06 10:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0003_numberrange'),
        ('core', '0014_paymentterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, help_text='Dokumentnummer (z.B. R26-00001)', max_length=32, verbose_name='Nummer')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('SENT', 'Versendet'), ('ACCEPTED', 'Akzeptiert'), ('REJECTED', 'Abgelehnt'), ('CANCELLED', 'Storniert'), ('OPEN', 'Offen'), ('PAID', 'Bezahlt'), ('OVERDUE', 'Überfällig')], db_index=True, max_length=32, verbose_name='Status')),
                ('issue_date', models.DateField(help_text='Datum der Belegausstellung', verbose_name='Belegdatum')),
                ('due_date', models.DateField(blank=True, help_text='Fälligkeitsdatum (erforderlich bei Dokumenttypen mit requires_due_date=True)', null=True, verbose_name='Fälligkeitsdatum')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Zeitpunkt der Zahlung', null=True, verbose_name='Bezahlt am')),
                ('payment_term_snapshot', models.JSONField(blank=True, help_text='JSON-Snapshot der Zahlungsbedingung zum Zeitpunkt der Belegausstellung', null=True, verbose_name='Zahlungsbedingung-Snapshot')),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gesamtbetrag netto', max_digits=12, verbose_name='Nettobetrag')),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gesamtbetrag Steuer', max_digits=12, verbose_name='Steuerbetrag')),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gesamtbetrag brutto', max_digits=12, verbose_name='Bruttobetrag')),
                ('notes_internal', models.TextField(blank=True, default='', help_text='Interne Notizen (nicht für Kunden sichtbar)', verbose_name='Interne Notizen')),
                ('notes_public', models.TextField(blank=True, default='', help_text='Öffentliche Notizen (auf Beleg sichtbar)', verbose_name='Öffentliche Notizen')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='core.mandant', verbose_name='Mandant')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='auftragsverwaltung.documenttype', verbose_name='Dokumenttyp')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='core.paymentterm', verbose_name='Zahlungsbedingung')),
                ('source_document', models.ForeignKey(blank=True, help_text='Referenz auf das ursprüngliche Dokument (erforderlich bei is_correction=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_documents', to='auftragsverwaltung.salesdocument', verbose_name='Quelldokument')),
            ],
            options={
                'verbose_name': 'Verkaufsbeleg',
                'verbose_name_plural': 'Verkaufsbelege',
                'ordering': ['-issue_date', '-id'],
                'indexes': [models.Index(fields=['company', 'document_type'], name='auftragsver_company_0a66d0_idx'), models.Index(fields=['company', 'status'], name='auftragsver_company_f08be6_idx'), models.Index(fields=['-issue_date'], name='auftragsver_issue_d_237e37_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type', 'number'), name='unique_salesdocument_number_per_company_doctype', violation_error_message='Diese Nummer existiert bereits für diesen Mandanten und Dokumenttyp.')],
            },
        ),
    ]
