# Generated by Django 5.2.11 on 2026-02-06 10:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0004_salesdocument'),
        ('core', '0016_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_no', models.IntegerField(help_text='Eindeutige Positionsnummer innerhalb des Dokuments', verbose_name='Positionsnummer')),
                ('line_type', models.CharField(choices=[('NORMAL', 'Normal'), ('OPTIONAL', 'Optional'), ('ALTERNATIVE', 'Alternative')], max_length=20, verbose_name='Positionstyp')),
                ('is_selected', models.BooleanField(help_text='Gibt an, ob diese Position ausgewählt ist (relevant für OPTIONAL/ALTERNATIVE)', verbose_name='Ausgewählt')),
                ('description', models.TextField(help_text='Positionsbeschreibung', verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Menge')),
                ('unit_price_net', models.DecimalField(decimal_places=2, help_text='Snapshot des Netto-Stückpreises zum Zeitpunkt der Positionsanlage', max_digits=12, verbose_name='Netto-Stückpreis (Snapshot)')),
                ('is_discountable', models.BooleanField(default=True, help_text='Gibt an, ob diese Position rabattfähig ist', verbose_name='Rabattfähig')),
                ('line_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Zeilenbetrag netto', max_digits=12, verbose_name='Nettobetrag')),
                ('line_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Zeilenbetrag Steuer', max_digits=12, verbose_name='Steuerbetrag')),
                ('line_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Zeilenbetrag brutto', max_digits=12, verbose_name='Bruttobetrag')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='auftragsverwaltung.salesdocument', verbose_name='Dokument')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_document_lines', to='core.item', verbose_name='Artikel/Leistung')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_document_lines', to='core.taxrate', verbose_name='Steuersatz')),
            ],
            options={
                'verbose_name': 'Dokumentposition',
                'verbose_name_plural': 'Dokumentpositionen',
                'ordering': ['document', 'position_no'],
                'indexes': [models.Index(fields=['document'], name='auftragsver_documen_b2c425_idx'), models.Index(fields=['document', 'position_no'], name='auftragsver_documen_6c04d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'position_no'), name='unique_position_no_per_document', violation_error_message='Diese Positionsnummer existiert bereits für dieses Dokument.')],
            },
        ),
    ]
