# Generated by Django 5.2.11 on 2026-02-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0005_salesdocumentline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COPIED_FROM', 'Kopiert von'), ('DERIVED_FROM', 'Abgeleitet von'), ('CORRECTION_OF', 'Korrektur von')], help_text='Art der Beziehung zwischen Ziel- und Quelldokument', max_length=20, verbose_name='Rolle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('source_document', models.ForeignKey(help_text='Das Ursprungsdokument', on_delete=django.db.models.deletion.PROTECT, related_name='sources_as_source', to='auftragsverwaltung.salesdocument', verbose_name='Quelldokument')),
                ('target_document', models.ForeignKey(help_text='Das Dokument, für das die Herkunft gespeichert wird', on_delete=django.db.models.deletion.PROTECT, related_name='sources_as_target', to='auftragsverwaltung.salesdocument', verbose_name='Zieldokument')),
            ],
            options={
                'verbose_name': 'Dokumentherkunft',
                'verbose_name_plural': 'Dokumentherkünfte',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_document'], name='auftragsver_target__fb80c7_idx'), models.Index(fields=['source_document'], name='auftragsver_source__d5c10f_idx'), models.Index(fields=['target_document', 'role'], name='auftragsver_target__4a04b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('target_document', 'source_document', 'role'), name='unique_document_source_per_target_source_role', violation_error_message='Diese Dokumentherkunft existiert bereits.'), models.CheckConstraint(condition=models.Q(('target_document', models.F('source_document')), _negated=True), name='prevent_self_reference_document_source', violation_error_message='Ein Dokument kann nicht auf sich selbst verweisen.')],
            },
        ),
    ]
