# Generated by Django 5.2.11 on 2026-02-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0006_salesdocumentsource'),
        ('core', '0019_rename_core_item_article_idx_core_item_article_e3fd5c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bezeichnung des Vertrags', max_length=200, verbose_name='Vertragsname')),
                ('currency', models.CharField(default='EUR', help_text='Währung (z.B. EUR)', max_length=3, verbose_name='Währung')),
                ('interval', models.CharField(choices=[('MONTHLY', 'Monatlich'), ('QUARTERLY', 'Quartalsweise'), ('SEMI_ANNUAL', 'Halbjährlich'), ('ANNUAL', 'Jährlich')], help_text='Intervall für wiederkehrende Abrechnung', max_length=20, verbose_name='Abrechnungsintervall')),
                ('start_date', models.DateField(help_text='Vertragsbeginn', verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, help_text='Vertragsende (optional, unbefristet wenn leer)', null=True, verbose_name='Enddatum')),
                ('next_run_date', models.DateField(help_text='Datum der nächsten Rechnungserzeugung', verbose_name='Nächstes Ausführungsdatum')),
                ('last_run_date', models.DateField(blank=True, help_text='Datum der letzten Rechnungserzeugung', null=True, verbose_name='Letztes Ausführungsdatum')),
                ('is_active', models.BooleanField(default=True, help_text='Gibt an, ob dieser Vertrag aktiv ist', verbose_name='Aktiv')),
                ('auto_finalize', models.BooleanField(default=False, help_text='Soll die Rechnung automatisch finalisiert werden?', verbose_name='Automatisch finalisieren')),
                ('auto_send', models.BooleanField(default=False, help_text='Soll die Rechnung automatisch versendet werden?', verbose_name='Automatisch versenden')),
                ('reference', models.CharField(blank=True, default='', help_text='Externe Referenz oder Vertragsnummer', max_length=100, verbose_name='Referenz')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.mandant', verbose_name='Mandant')),
                ('customer', models.ForeignKey(help_text='Kunde oder Adresse für diesen Vertrag', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.adresse', verbose_name='Kunde')),
                ('document_type', models.ForeignKey(help_text='Dokumenttyp für die generierten Rechnungen (Standard: Rechnungstyp)', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='auftragsverwaltung.documenttype', verbose_name='Dokumenttyp')),
                ('payment_term', models.ForeignKey(blank=True, help_text='Zahlungsbedingung (Standard via Company)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.paymentterm', verbose_name='Zahlungsbedingung')),
            ],
            options={
                'verbose_name': 'Vertrag',
                'verbose_name_plural': 'Verträge',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_no', models.IntegerField(help_text='Positionsnummer innerhalb des Vertrags', verbose_name='Positionsnummer')),
                ('description', models.TextField(help_text='Positionsbeschreibung', verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Menge')),
                ('unit_price_net', models.DecimalField(decimal_places=2, help_text='Netto-Stückpreis (Snapshot)', max_digits=12, verbose_name='Netto-Stückpreis')),
                ('is_discountable', models.BooleanField(default=True, help_text='Gibt an, ob diese Position rabattfähig ist', verbose_name='Rabattfähig')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='auftragsverwaltung.contract', verbose_name='Vertrag')),
                ('cost_type_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines_cost_type_1', to='core.kostenart', verbose_name='Kostenart 1')),
                ('cost_type_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines_cost_type_2', to='core.kostenart', verbose_name='Kostenart 2')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='core.item', verbose_name='Artikel/Leistung')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='core.taxrate', verbose_name='Steuersatz')),
            ],
            options={
                'verbose_name': 'Vertragsposition',
                'verbose_name_plural': 'Vertragspositionen',
                'ordering': ['contract', 'position_no'],
            },
        ),
        migrations.CreateModel(
            name='ContractRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(help_text='Datum der Vertragsausführung', verbose_name='Ausführungsdatum')),
                ('status', models.CharField(choices=[('SUCCESS', 'Erfolgreich'), ('FAILED', 'Fehlgeschlagen'), ('SKIPPED', 'Übersprungen')], max_length=20, verbose_name='Status')),
                ('message', models.TextField(blank=True, default='', help_text='Fehlermeldung oder Statusnachricht', verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='auftragsverwaltung.contract', verbose_name='Vertrag')),
                ('document', models.ForeignKey(blank=True, help_text='Generiertes Verkaufsdokument', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_runs', to='auftragsverwaltung.salesdocument', verbose_name='Dokument')),
            ],
            options={
                'verbose_name': 'Vertragsausführung',
                'verbose_name_plural': 'Vertragsausführungen',
                'ordering': ['-run_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'is_active'], name='auftragsver_company_e3310f_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['next_run_date'], name='auftragsver_next_ru_61f27e_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'customer'], name='auftragsver_company_f49f75_idx'),
        ),
        migrations.AddIndex(
            model_name='contractline',
            index=models.Index(fields=['contract'], name='auftragsver_contrac_e4e4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='contractline',
            index=models.Index(fields=['contract', 'position_no'], name='auftragsver_contrac_57840a_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractline',
            constraint=models.UniqueConstraint(fields=('contract', 'position_no'), name='unique_position_no_per_contract', violation_error_message='Diese Positionsnummer existiert bereits für diesen Vertrag.'),
        ),
        migrations.AddIndex(
            model_name='contractrun',
            index=models.Index(fields=['contract'], name='auftragsver_contrac_9f9f78_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrun',
            index=models.Index(fields=['contract', 'run_date'], name='auftragsver_contrac_5a0ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrun',
            index=models.Index(fields=['-run_date'], name='auftragsver_run_dat_fcf9f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractrun',
            constraint=models.UniqueConstraint(fields=('contract', 'run_date'), name='unique_contract_run_per_contract_date', violation_error_message='Es existiert bereits eine Ausführung für diesen Vertrag und dieses Datum.'),
        ),
    ]
