# Generated by Django 5.2.9 on 2026-02-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0007_contract_contractline_contractrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='footer_text',
            field=models.TextField(blank=True, default='', help_text='Freitext für die Fußzeile des Dokuments', verbose_name='Fußzeile'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='header_text',
            field=models.TextField(blank=True, default='', help_text='Freitext für die Kopfzeile des Dokuments', verbose_name='Kopfzeile'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='payment_term_text',
            field=models.TextField(blank=True, default='', help_text="Freitext für die Zahlungsbedingungen (z.B. 'Zahlbar innerhalb von 14 Tagen ohne Abzug')", verbose_name='Zahlungsbedingungstext'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='reference_number',
            field=models.CharField(blank=True, default='', help_text='Externe Referenznummer (z.B. Bestellnummer des Kunden)', max_length=50, verbose_name='Referenznummer'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Betreff oder Kurzbeschreibung des Dokuments', max_length=200, verbose_name='Betreff'),
        ),
    ]
