# Generated by Django 5.2.11 on 2026-02-06 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0009_add_document_types_data'),
        ('core', '0022_add_activity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Kunde oder Adresse für dieses Dokument', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='core.adresse', verbose_name='Kunde'),
        ),
        migrations.AddIndex(
            model_name='salesdocument',
            index=models.Index(fields=['customer'], name='auftragsver_custome_a29572_idx'),
        ),
    ]
