# Generated by Django 5.2.9 on 2026-02-06 19:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0010_add_customer_to_salesdocument'),
        ('core', '0022_add_activity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocumentline',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rabatt in Prozent (z.B. 10.00 für 10% Rabatt)', max_digits=5, verbose_name='Rabatt (%)'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='kostenart1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_document_lines_kostenart1', to='core.kostenart', verbose_name='Kostenart 1'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='kostenart2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_document_lines_kostenart2', to='core.kostenart', verbose_name='Kostenart 2'),
        ),
    ]
