# Generated by Django 5.2.11 on 2026-02-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0011_salesdocumentline_discount_and_more'),
        ('core', '0022_add_activity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Eindeutiger Kurzbezeichner (z.B. 'standard_header')", verbose_name='Schlüssel')),
                ('title', models.CharField(help_text='Anzeigename für die Auswahl im Dropdown', max_length=200, verbose_name='Titel')),
                ('type', models.CharField(choices=[('HEADER', 'Kopftext'), ('FOOTER', 'Fußtext'), ('BOTH', 'Kopf- und Fußtext')], help_text='Verwendungszweck des Textbausteins', max_length=10, verbose_name='Typ')),
                ('content', models.TextField(help_text='Textinhalt des Bausteins', verbose_name='Inhalt')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive Bausteine werden nicht in der Auswahl angezeigt', verbose_name='Aktiv')),
                ('sort_order', models.IntegerField(default=0, help_text='Sortierreihenfolge (niedrigere Werte zuerst)', verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text_templates', to='core.mandant', verbose_name='Mandant')),
            ],
            options={
                'verbose_name': 'Textbaustein',
                'verbose_name_plural': 'Textbausteine',
                'ordering': ['type', 'sort_order', 'title'],
                'indexes': [models.Index(fields=['company', 'type', 'is_active'], name='auftragsver_company_68b810_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'key'), name='unique_texttemplate_company_key', violation_error_message='Ein Textbaustein mit diesem Schlüssel existiert bereits für diesen Mandanten.')],
            },
        ),
    ]
