# Generated by Django 5.2.11 on 2026-02-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0012_texttemplate'),
        ('core', '0022_add_activity_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberrange',
            options={'ordering': ['company', 'target', 'document_type'], 'verbose_name': 'Nummernkreis', 'verbose_name_plural': 'Nummernkreise'},
        ),
        migrations.RemoveConstraint(
            model_name='numberrange',
            name='unique_numberrange_per_company_doctype',
        ),
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, db_index=True, help_text='Vertragsnummer (z.B. V26-00001), automatisch generiert falls leer', max_length=32, null=True, verbose_name='Vertragsnummer'),
        ),
        migrations.AddField(
            model_name='numberrange',
            name='target',
            field=models.CharField(choices=[('DOCUMENT', 'Dokument'), ('CONTRACT', 'Vertrag')], default='DOCUMENT', help_text='Target type: DOCUMENT for SalesDocument, CONTRACT for Contract', max_length=10, verbose_name='Ziel'),
        ),
        migrations.AlterField(
            model_name='numberrange',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Required for DOCUMENT target, not used for CONTRACT target', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='number_ranges', to='auftragsverwaltung.documenttype', verbose_name='Dokumenttyp'),
        ),
        migrations.AddIndex(
            model_name='numberrange',
            index=models.Index(fields=['company', 'target'], name='auftragsver_company_4c8f01_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_contract_number_per_company', violation_error_message='Diese Vertragsnummer existiert bereits für diesen Mandanten.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.UniqueConstraint(condition=models.Q(('target', 'DOCUMENT')), fields=('company', 'document_type'), name='unique_numberrange_per_company_doctype', violation_error_message='Es kann nur einen Nummernkreis pro Mandant und Dokumenttyp geben.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.UniqueConstraint(condition=models.Q(('target', 'CONTRACT')), fields=('company',), name='unique_numberrange_contract_per_company', violation_error_message='Es kann nur einen Vertrags-Nummernkreis pro Mandant geben.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_type__isnull', False), ('target', 'DOCUMENT')), ('target', 'CONTRACT'), _connector='OR'), name='numberrange_document_requires_doctype', violation_error_message='Dokumenttyp ist erforderlich für DOCUMENT-Nummernkreis.'),
        ),
    ]
