# Generated by Django 5.2.11 on 2026-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0013_extend_numberrange_for_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocumentline',
            name='long_text',
            field=models.TextField(blank=True, default='', help_text='Detaillierter Langtext', verbose_name='Langtext'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='short_text_1',
            field=models.CharField(blank=True, default='', help_text='Primärer Kurztext', max_length=200, verbose_name='Kurztext 1'),
        ),
        migrations.AddField(
            model_name='salesdocumentline',
            name='short_text_2',
            field=models.CharField(blank=True, default='', help_text='Optionaler zweiter Kurztext', max_length=200, verbose_name='Kurztext 2'),
        ),
        migrations.AlterField(
            model_name='salesdocumentline',
            name='description',
            field=models.TextField(help_text='Positionsbeschreibung (generiert aus Kurztexten)', verbose_name='Beschreibung'),
        ),
    ]
