# Generated by Django 5.2.9 on 2026-02-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0014_add_text_fields_to_salesdocumentline'),
        ('core', '0023_add_unit_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocumentline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_document_lines', to='core.unit', verbose_name='Mengeneinheit'),
        ),
    ]
