# Generated by Django 5.2.11 on 2026-02-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0015_salesdocumentline_unit'),
        ('core', '0025_add_handelsregister_to_mandant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(db_index=True, help_text='Datum der Leistungserbringung', verbose_name='Leistungsdatum')),
                ('duration_minutes', models.IntegerField(help_text='Dauer der Leistung in Minuten (muss > 0 sein)', verbose_name='Dauer (Minuten)')),
                ('description', models.TextField(help_text='Beschreibung der durchgeführten Tätigkeit', verbose_name='Tätigkeitsbeschreibung')),
                ('is_travel_cost', models.BooleanField(default=False, help_text='Handelt es sich um Anfahrtszeit?', verbose_name='Anfahrt')),
                ('is_billed', models.BooleanField(db_index=True, default=False, help_text='Wurde diese Leistung bereits abgerechnet?', verbose_name='Abgerechnet')),
                ('billed_at', models.DateTimeField(blank=True, help_text='Zeitpunkt der Abrechnung', null=True, verbose_name='Abgerechnet am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='core.mandant', verbose_name='Mandant')),
                ('customer', models.ForeignKey(help_text='Kunde für diese Zeiterfassung', on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='core.adresse', verbose_name='Kunde')),
                ('order', models.ForeignKey(help_text='Auftrag (SalesDocument vom Typ ORDER)', on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='auftragsverwaltung.salesdocument', verbose_name='Auftrag')),
                ('performed_by', models.ForeignKey(help_text='Benutzer der die Arbeit ausgeführt hat', on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Ausführender Benutzer')),
            ],
            options={
                'verbose_name': 'Zeiterfassung',
                'verbose_name_plural': 'Zeiterfassungen',
                'ordering': ['-service_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'service_date'], name='auftragsver_company_7a0517_idx'), models.Index(fields=['customer'], name='auftragsver_custome_09bb68_idx'), models.Index(fields=['order'], name='auftragsver_order_i_e02531_idx'), models.Index(fields=['performed_by', 'service_date'], name='auftragsver_perform_e1315c_idx'), models.Index(fields=['-service_date', '-created_at'], name='auftragsver_service_36885d_idx'), models.Index(fields=['is_billed'], name='auftragsver_is_bill_76e6f7_idx')],
            },
        ),
    ]
