# Generated by Django 5.2.12 on 2026-04-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0016_add_timeentry_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractline',
            name='long_text',
            field=models.TextField(blank=True, default='', help_text='Detaillierter Langtext', verbose_name='Langtext'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='short_text_1',
            field=models.CharField(blank=True, default='', help_text='Primärer Kurztext', max_length=200, verbose_name='Kurztext 1'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='short_text_2',
            field=models.CharField(blank=True, default='', help_text='Optionaler zweiter Kurztext', max_length=200, verbose_name='Kurztext 2'),
        ),
    ]
