# Generated by Django 5.2.12 on 2026-04-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0017_add_text_fields_to_contractline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='performance_date_from',
            field=models.DateField(blank=True, help_text='Beginn des Leistungszeitraums (bei Einzeltag: nur dieses Feld setzen)', null=True, verbose_name='Leistungszeitraum von'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='performance_date_to',
            field=models.DateField(blank=True, help_text='Ende des Leistungszeitraums (optional, nur bei Zeitraum)', null=True, verbose_name='Leistungszeitraum bis'),
        ),
    ]
