# Generated by Django 5.2.12 on 2026-04-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0018_add_performance_date_fields'),
        ('core', '0031_alter_item_article_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='numberrange',
            name='numberrange_document_requires_doctype',
        ),
        migrations.AlterField(
            model_name='numberrange',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Required for DOCUMENT and CONTRACT targets, not used for ITEM target', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='number_ranges', to='core.mandant', verbose_name='Mandant'),
        ),
        migrations.AlterField(
            model_name='numberrange',
            name='target',
            field=models.CharField(choices=[('DOCUMENT', 'Dokument'), ('CONTRACT', 'Vertrag'), ('ITEM', 'Artikel')], default='DOCUMENT', help_text='Target type: DOCUMENT for SalesDocument, CONTRACT for Contract', max_length=10, verbose_name='Ziel'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.UniqueConstraint(condition=models.Q(('target', 'ITEM')), fields=('target',), name='unique_numberrange_item_global', violation_error_message='Es kann nur einen globalen Artikel-Nummernkreis geben.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_type__isnull', False), ('target', 'DOCUMENT')), ('target', 'CONTRACT'), ('target', 'ITEM'), _connector='OR'), name='numberrange_document_requires_doctype', violation_error_message='Dokumenttyp ist erforderlich für DOCUMENT-Nummernkreis.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(('target', 'ITEM'), ('company__isnull', False), _connector='OR'), name='numberrange_company_required_for_non_item', violation_error_message='Mandant ist erforderlich für DOCUMENT und CONTRACT Nummernkreise.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', False), ('target', 'ITEM'), _negated=True), name='numberrange_item_no_company', violation_error_message='Artikel-Nummernkreis darf keinen Mandanten haben (global).'),
        ),
    ]
