# Generated by Django 5.2.12 on 2026-04-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0019_remove_numberrange_numberrange_document_requires_doctype_and_more'),
        ('core', '0031_alter_item_article_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='numberrange',
            name='numberrange_document_requires_doctype',
        ),
        migrations.RemoveConstraint(
            model_name='numberrange',
            name='numberrange_company_required_for_non_item',
        ),
        migrations.RemoveConstraint(
            model_name='numberrange',
            name='numberrange_item_no_company',
        ),
        migrations.AlterField(
            model_name='numberrange',
            name='target',
            field=models.CharField(choices=[('DOCUMENT', 'Dokument'), ('CONTRACT', 'Vertrag'), ('ITEM', 'Artikel'), ('CUSTOMER', 'Kunde')], default='DOCUMENT', help_text='Target type: DOCUMENT for SalesDocument, CONTRACT for Contract', max_length=10, verbose_name='Ziel'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.UniqueConstraint(condition=models.Q(('target', 'CUSTOMER')), fields=('target',), name='unique_numberrange_customer_global', violation_error_message='Es kann nur einen globalen Kunden-Nummernkreis geben.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_type__isnull', False), ('target', 'DOCUMENT')), ('target', 'CONTRACT'), ('target', 'ITEM'), ('target', 'CUSTOMER'), _connector='OR'), name='numberrange_document_requires_doctype', violation_error_message='Dokumenttyp ist erforderlich für DOCUMENT-Nummernkreis.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(('target', 'ITEM'), ('target', 'CUSTOMER'), ('company__isnull', False), _connector='OR'), name='numberrange_company_required_for_non_item', violation_error_message='Mandant ist erforderlich für DOCUMENT und CONTRACT Nummernkreise.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', False), ('target__in', ['ITEM', 'CUSTOMER']), _negated=True), name='numberrange_item_no_company', violation_error_message='Artikel- und Kunden-Nummernkreise dürfen keinen Mandanten haben (global).'),
        ),
    ]
