# Generated by Django 5.2.16 on 2026-08-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0021_create_default_customer_numberrange'),
        ('core', '0032_add_debitor_number_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='core.unit', verbose_name='Mengeneinheit'),
        ),
    ]
