# Generated by Django 5.2.16 on 2026-08-27 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0023_migrate_contractline_description_to_texts'),
        ('core', '0034_projekt_company_projekt_kunde'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='projekt',
            field=models.ForeignKey(blank=True, help_text='Optionales Projekt, dem die Leistung zugeordnet wird', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='core.projekt', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Optionaler Auftrag (SalesDocument vom Typ ORDER)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='auftragsverwaltung.salesdocument', verbose_name='Auftrag'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['projekt'], name='auftragsver_projekt_4e5c15_idx'),
        ),
    ]
