# Generated by Django 5.2.16 on 2026-08-29 12:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0024_timeentry_projekt_alter_timeentry_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Summe aller Positionsrabatte (bereits in total_net abgezogen)', max_digits=12, verbose_name='Rabattbetrag'),
        ),
        migrations.AlterField(
            model_name='salesdocumentline',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rabatt in Prozent (z.B. 10.00 für 10% Rabatt)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Rabatt (%)'),
        ),
    ]
