# Generated by Django 5.2.16 on 2026-08-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0025_salesdocument_total_discount_and_more'),
        ('core', '0036_kostenart_aufwandskonto_kostenart_erloeskonto_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='numberrange',
            name='numberrange_document_requires_doctype',
        ),
        migrations.RemoveConstraint(
            model_name='numberrange',
            name='numberrange_company_required_for_non_item',
        ),
        migrations.RemoveConstraint(
            model_name='numberrange',
            name='numberrange_item_no_company',
        ),
        migrations.AddField(
            model_name='numberrange',
            name='start_seq',
            field=models.IntegerField(default=0, help_text='Erster zu vergebender Sequenzwert. Bei 0 beginnt die Vergabe wie bisher bei 1; für Personenkonten z. B. 10000 bzw. 70000.', verbose_name='Startwert'),
        ),
        migrations.AlterField(
            model_name='numberrange',
            name='target',
            field=models.CharField(choices=[('DOCUMENT', 'Dokument'), ('CONTRACT', 'Vertrag'), ('ITEM', 'Artikel'), ('CUSTOMER', 'Kunde'), ('SUPPLIER', 'Lieferant')], default='DOCUMENT', help_text='Target type: DOCUMENT for SalesDocument, CONTRACT for Contract', max_length=10, verbose_name='Ziel'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.UniqueConstraint(condition=models.Q(('target', 'SUPPLIER')), fields=('target',), name='unique_numberrange_supplier_global', violation_error_message='Es kann nur einen globalen Lieferanten-Nummernkreis geben.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_type__isnull', False), ('target', 'DOCUMENT')), ('target', 'CONTRACT'), ('target', 'ITEM'), ('target', 'CUSTOMER'), ('target', 'SUPPLIER'), _connector='OR'), name='numberrange_document_requires_doctype', violation_error_message='Dokumenttyp ist erforderlich für DOCUMENT-Nummernkreis.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(('target', 'ITEM'), ('target', 'CUSTOMER'), ('target', 'SUPPLIER'), ('company__isnull', False), _connector='OR'), name='numberrange_company_required_for_non_item', violation_error_message='Mandant ist erforderlich für DOCUMENT und CONTRACT Nummernkreise.'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', False), ('target__in', ['ITEM', 'CUSTOMER', 'SUPPLIER']), _negated=True), name='numberrange_item_no_company', violation_error_message='Artikel-, Kunden- und Lieferanten-Nummernkreise dürfen keinen Mandanten haben (global).'),
        ),
    ]
