# Generated by Django 5.2.16 on 2026-08-30 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0026_remove_numberrange_numberrange_document_requires_doctype_and_more'),
        ('core', '0038_projekt_billing_item_projekt_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='invoice_line',
            field=models.ForeignKey(blank=True, help_text='Position der Rechnung, auf der diese Stunde abgerechnet wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='auftragsverwaltung.salesdocumentline', verbose_name='Rechnungsposition'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['invoice_line'], name='auftragsver_invoice_49d00b_idx'),
        ),
    ]
