# Generated by Django 5.2.16 on 2026-08-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0027_timeentry_invoice_line_and_more'),
        ('core', '0038_projekt_billing_item_projekt_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='projekt',
            field=models.ForeignKey(blank=True, help_text='Optionale Zuordnung zu einem Projekt; steuert die Belegliste und die Fakturasummen auf der Projektseite.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='core.projekt', verbose_name='Projekt'),
        ),
        migrations.AddIndex(
            model_name='salesdocument',
            index=models.Index(fields=['projekt'], name='auftragsver_projekt_dbadb0_idx'),
        ),
    ]
