# Generated by Django 5.2.11 on 2026-02-27 22:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auftragsverwaltung', '0016_add_timeentry_model'),
        ('core', '0026_projekt_projektfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('ust_id', models.CharField(blank=True, default='', max_length=50, verbose_name='USt-IdNr.')),
                ('steuer_nr', models.CharField(blank=True, default='', max_length=50, verbose_name='Steuernummer')),
                ('adresse_street', models.CharField(blank=True, default='', max_length=200, verbose_name='Straße')),
                ('adresse_zip', models.CharField(blank=True, default='', max_length=20, verbose_name='PLZ')),
                ('adresse_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ort')),
                ('adresse_country', models.CharField(blank=True, default='DE', max_length=100, verbose_name='Land')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon')),
                ('bank_iban', models.CharField(blank=True, default='', max_length=34, verbose_name='IBAN')),
                ('bank_bic', models.CharField(blank=True, default='', max_length=11, verbose_name='BIC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
            ],
            options={
                'verbose_name': 'Lieferant',
                'verbose_name_plural': 'Lieferanten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, verbose_name='Rechnungsnummer')),
                ('invoice_date', models.DateField(verbose_name='Rechnungsdatum')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Währung')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Nettobetrag')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Umsatzsteuer')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bruttobetrag')),
                ('tax_rate_summary', models.JSONField(blank=True, null=True, verbose_name='Steuersatz-Zusammenfassung')),
                ('payment_terms_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Zahlungsbedingungen')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fälligkeit')),
                ('payment_reference', models.CharField(blank=True, default='', max_length=200, verbose_name='Verwendungszweck')),
                ('iban_from_invoice', models.CharField(blank=True, default='', max_length=34, verbose_name='IBAN (aus Rechnung)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lieferantenwesen/invoices/', verbose_name='PDF-Datei')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('EXTRACTED', 'Extrahiert'), ('IN_REVIEW', 'In Prüfung'), ('APPROVED', 'Freigegeben'), ('REJECTED', 'Abgelehnt')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('approval_comment', models.TextField(blank=True, default='', verbose_name='Freigabe-Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben am')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgelehnt am')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicein_approved', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben von')),
                ('cost_type_main', models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicein_main', to='core.kostenart', verbose_name='Hauptkostenart')),
                ('cost_type_sub', models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicein_sub', to='core.kostenart', verbose_name='Unterkostenart')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicein_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('order', models.ForeignKey(blank=True, help_text='Optionale Zuordnung zu einem Auftrag (Controlling / Rentabilität)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoices', to='auftragsverwaltung.salesdocument', verbose_name='Auftrag')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicein_rejected', to=settings.AUTH_USER_MODEL, verbose_name='Abgelehnt von')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicein_updated', to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='lieferantenwesen.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Eingangsrechnung',
                'verbose_name_plural': 'Eingangsrechnungen',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceInLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_no', models.PositiveSmallIntegerField(default=1, verbose_name='Position')),
                ('description', models.CharField(max_length=500, verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Menge')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Einheit')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Einzelpreis')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nettobetrag')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, verbose_name='Steuersatz (%)')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Umsatzsteuer')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bruttobetrag')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='lieferantenwesen.invoicein', verbose_name='Rechnung')),
            ],
            options={
                'verbose_name': 'Rechnungsposition',
                'verbose_name_plural': 'Rechnungspositionen',
                'ordering': ['position_no'],
            },
        ),
    ]
