# Generated by Django 5.2.11 on 2026-03-01 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_projekt_projektfile'),
        ('lieferantenwesen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicein',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'adressen_type': 'LIEFERANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_lieferantenwesen', to='core.adresse', verbose_name='Lieferant'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
