# Generated by Django 5.2.11 on 2026-03-01 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_projekt_projektfile'),
        ('lieferantenwesen', '0002_change_supplier_to_adresse'),
        ('vermietung', '0036_add_stellplatzbetrag_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicein',
            name='allocable_to_tenants',
            field=models.BooleanField(default=True, help_text='Kann auf Mieter umgelegt werden', verbose_name='Umlagefähig'),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notizen'),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Zahlungsdatum'),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Referenznummer'),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='rental_object',
            field=models.ForeignKey(blank=True, help_text='Zuordnung zu einem Mietobjekt (für Vermietungs-Kontext)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_in', to='vermietung.mietobjekt', verbose_name='Mietobjekt'),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='service_period_from',
            field=models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum von'),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='service_period_to',
            field=models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum bis'),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Betreff'),
        ),
        migrations.AddField(
            model_name='invoiceinline',
            name='cost_type_main_line',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoiceinline_main', to='core.kostenart', verbose_name='Kostenart 1 (Hauptkostenart)'),
        ),
        migrations.AddField(
            model_name='invoiceinline',
            name='cost_type_sub_line',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoiceinline_sub', to='core.kostenart', verbose_name='Kostenart 2 (Unterkostenart)'),
        ),
        migrations.AlterField(
            model_name='invoicein',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Entwurf'), ('EXTRACTED', 'Extrahiert'), ('IN_REVIEW', 'In Prüfung'), ('APPROVED', 'Freigegeben'), ('REJECTED', 'Abgelehnt'), ('PAID', 'Bezahlt')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
