# Generated by Django 5.2.16 on 2026-08-29 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0026_remove_numberrange_numberrange_document_requires_doctype_and_more'),
        ('core', '0036_kostenart_aufwandskonto_kostenart_erloeskonto_and_more'),
        ('lieferantenwesen', '0004_migrate_eingangsrechnung_data'),
        ('vermietung', '0038_migrate_dokument_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicein',
            name='export_batch_id',
            field=models.CharField(blank=True, default='', help_text='ID der Export-Charge des letzten Exports', max_length=100, verbose_name='Export-Batch-ID'),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='export_status',
            field=models.CharField(choices=[('OPEN', 'Offen'), ('EXPORTED', 'Exportiert'), ('ERROR', 'Fehler')], default='OPEN', help_text='Status des DATEV-Buchungsstapel-Exports', max_length=20, verbose_name='Export-Status'),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='exported_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt des letzten erfolgreichen Exports', null=True, verbose_name='Exportiert am'),
        ),
        migrations.AddIndex(
            model_name='invoicein',
            index=models.Index(fields=['invoice_date', 'status'], name='lieferanten_invoice_549566_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicein',
            index=models.Index(fields=['export_status'], name='lieferanten_export__946edb_idx'),
        ),
    ]
