# Generated by Django 5.2.16 on 2026-08-30 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftragsverwaltung', '0026_remove_numberrange_numberrange_document_requires_doctype_and_more'),
        ('core', '0037_datev_personenkonten'),
        ('lieferantenwesen', '0005_invoicein_export_batch_id_invoicein_export_status_and_more'),
        ('vermietung', '0038_migrate_dokument_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicein',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Mandant, zu dem der Aufwand gehört. Steuert die Auswahl im DATEV-Buchungsstapel.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_invoices', to='core.mandant', verbose_name='Mandant'),
        ),
        migrations.AddIndex(
            model_name='invoicein',
            index=models.Index(fields=['company'], name='lieferanten_company_cee668_idx'),
        ),
    ]
