# Generated by Django 5.0.1 on 2025-12-22 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MietObjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('GEBAEUDE', 'Gebäude'), ('RAUM', 'Raum'), ('CONTAINER', 'Container'), ('STELLPLATZ', 'Stellplatz'), ('KFZ', 'KFZ'), ('SONSTIGES', 'Sonstiges')], max_length=20)),
                ('beschreibung', models.TextField()),
                ('fläche', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('höhe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('breite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiefe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mietpreis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verfuegbar', models.BooleanField(default=True)),
                ('standort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adresse')),
            ],
        ),
    ]
