# Generated by Django 5.0.1 on 2025-12-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vermietung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertragsnummer', models.CharField(editable=False, help_text='Automatisch generierte Vertragsnummer im Format V-00000', max_length=10, unique=True, verbose_name='Vertragsnummer')),
                ('start', models.DateField(help_text='Startdatum des Vertrags (Pflicht)', verbose_name='Vertragsbeginn')),
                ('ende', models.DateField(blank=True, help_text='Enddatum des Vertrags (optional, NULL = offenes Ende)', null=True, verbose_name='Vertragsende')),
                ('miete', models.DecimalField(decimal_places=2, help_text='Monatliche Miete in EUR', max_digits=10, verbose_name='Miete')),
                ('kaution', models.DecimalField(decimal_places=2, help_text='Kaution in EUR', max_digits=10, verbose_name='Kaution')),
                ('mieter', models.ForeignKey(help_text="Nur Adressen vom Typ 'Kunde' können ausgewählt werden", limit_choices_to={'adressen_type': 'KUNDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='vertraege', to='core.adresse', verbose_name='Mieter')),
                ('mietobjekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vertraege', to='vermietung.mietobjekt', verbose_name='Mietobjekt')),
            ],
            options={
                'verbose_name': 'Vertrag',
                'verbose_name_plural': 'Verträge',
                'ordering': ['-start'],
            },
        ),
    ]
