# Generated by Django 5.0.1 on 2025-12-22 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0002_vertrag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uebergabeprotokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('EINZUG', 'Einzug'), ('AUSZUG', 'Auszug')], help_text='Art der Übergabe (Einzug oder Auszug)', max_length=10, verbose_name='Typ')),
                ('uebergabetag', models.DateField(help_text='Datum der Übergabe', verbose_name='Übergabetag')),
                ('zaehlerstand_strom', models.DecimalField(blank=True, decimal_places=2, help_text='Stromzählerstand in kWh', max_digits=10, null=True, verbose_name='Zählerstand Strom')),
                ('zaehlerstand_gas', models.DecimalField(blank=True, decimal_places=2, help_text='Gaszählerstand in m³', max_digits=10, null=True, verbose_name='Zählerstand Gas')),
                ('zaehlerstand_wasser', models.DecimalField(blank=True, decimal_places=2, help_text='Wasserzählerstand in m³', max_digits=10, null=True, verbose_name='Zählerstand Wasser')),
                ('anzahl_schluessel', models.IntegerField(default=0, help_text='Anzahl der übergebenen Schlüssel', verbose_name='Anzahl Schlüssel')),
                ('bemerkungen', models.TextField(blank=True, help_text='Allgemeine Bemerkungen zur Übergabe', verbose_name='Bemerkungen')),
                ('maengel', models.TextField(blank=True, help_text='Festgestellte Mängel bei der Übergabe', verbose_name='Mängel')),
                ('person_vermieter', models.CharField(blank=True, help_text='Name der Person auf Vermieterseite', max_length=200, verbose_name='Person Vermieter')),
                ('person_mieter', models.CharField(blank=True, help_text='Name der Person auf Mieterseite', max_length=200, verbose_name='Person Mieter')),
                ('mietobjekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uebergabeprotokolle', to='vermietung.mietobjekt', verbose_name='Mietobjekt')),
                ('vertrag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uebergabeprotokolle', to='vermietung.vertrag', verbose_name='Vertrag')),
            ],
            options={
                'verbose_name': 'Übergabeprotokoll',
                'verbose_name_plural': 'Übergabeprotokolle',
                'ordering': ['-uebergabetag'],
            },
        ),
    ]
