# Generated by Django 5.0.1 on 2025-12-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0003_uebergabeprotokoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertrag',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('ended', 'Beendet'), ('cancelled', 'Storniert')], default='active', help_text='Status des Vertrags', max_length=20, verbose_name='Status'),
        ),
    ]
