# Generated by Django 5.0.1 on 2025-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0004_vertrag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mietobjekt',
            name='kaution',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kautions-Vorgabe (Standard: 3x Miete)', max_digits=10, null=True, verbose_name='Kaution'),
        ),
    ]
