# Generated by Django 5.0.1 on 2025-12-23 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vermietung', '0004_vertrag_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='Der ursprüngliche Dateiname beim Upload', max_length=255, verbose_name='Originaler Dateiname')),
                ('storage_path', models.CharField(help_text='Relativer Pfad zur Datei im Filesystem', max_length=500, verbose_name='Speicherpfad')),
                ('file_size', models.IntegerField(help_text='Dateigröße in Bytes', verbose_name='Dateigröße')),
                ('mime_type', models.CharField(help_text='MIME-Type der Datei', max_length=100, verbose_name='MIME-Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt des Uploads', verbose_name='Hochgeladen am')),
                ('beschreibung', models.TextField(blank=True, help_text='Optional: Beschreibung des Dokuments', verbose_name='Beschreibung')),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='core.adresse', verbose_name='Adresse')),
                ('mietobjekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='vermietung.mietobjekt', verbose_name='Mietobjekt')),
                ('uebergabeprotokoll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='vermietung.uebergabeprotokoll', verbose_name='Übergabeprotokoll')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Benutzer, der die Datei hochgeladen hat', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
                ('vertrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='vermietung.vertrag', verbose_name='Vertrag')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
