<<<<<<< HEAD
=======
# Generated by Django 5.0.1 on 2025-12-23 06:39

>>>>>>> 04419d27d9db9cf2cc1727f44879bd48dbc7200c
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0005_dokument'),
        ('vermietung', '0005_mietobjekt_kaution'),
    ]

    operations = [
    ]

