<<<<<<< HEAD
# Generated by Django 5.0.1 on 2025-12-23 06:34
=======
# Generated by Django 5.0.1 on 2025-12-23 06:39
>>>>>>> 8319511b7a494785285b5beb3d66300a438588dc

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0005_dokument'),
        ('vermietung', '0005_mietobjekt_kaution'),
    ]

    operations = [
    ]
