<<<<<<< HEAD
# Generated by Django 5.0.1 on 2025-12-23 06:35
=======
# Generated by Django 5.0.1 on 2025-12-23 07:04
>>>>>>> 8319511b7a494785285b5beb3d66300a438588dc

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0006_merge_0005_dokument_0005_mietobjekt_kaution'),
    ]

    operations = [
        migrations.AddField(
            model_name='mietobjekt',
            name='nebenkosten',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
