# Generated by Django 5.2.9 on 2025-12-26 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0008_mietobjektbild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertrag',
            name='mietobjekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vertraege_legacy', to='vermietung.mietobjekt', verbose_name='Mietobjekt (Legacy)'),
        ),
        migrations.CreateModel(
            name='VertragsObjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Zuordnung', verbose_name='Erstellt am')),
                ('mietobjekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vertragsobjekte', to='vermietung.mietobjekt', verbose_name='Mietobjekt')),
                ('vertrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertragsobjekte', to='vermietung.vertrag', verbose_name='Vertrag')),
            ],
            options={
                'verbose_name': 'Vertragsobjekt',
                'verbose_name_plural': 'Vertragsobjekte',
                'ordering': ['created_at'],
                'unique_together': {('vertrag', 'mietobjekt')},
            },
        ),
    ]
