# Generated by Django 5.2.9 on 2025-12-26 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mailtemplate_smtpsettings'),
        ('vermietung', '0008_mietobjektbild'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitaet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text='Titel der Aktivität', max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, help_text='Detaillierte Beschreibung der Aktivität', verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('OFFEN', 'Offen'), ('IN_BEARBEITUNG', 'In Bearbeitung'), ('ERLEDIGT', 'Erledigt'), ('ABGEBROCHEN', 'Abgebrochen')], default='OFFEN', help_text='Status der Aktivität', max_length=20, verbose_name='Status')),
                ('prioritaet', models.CharField(choices=[('NIEDRIG', 'Niedrig'), ('NORMAL', 'Normal'), ('HOCH', 'Hoch')], default='NORMAL', help_text='Priorität der Aktivität', max_length=20, verbose_name='Priorität')),
                ('faellig_am', models.DateField(blank=True, help_text='Fälligkeitsdatum der Aktivität', null=True, verbose_name='Fällig am')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aktualisierung', verbose_name='Aktualisiert am')),
                ('assigned_supplier', models.ForeignKey(blank=True, help_text='Externer Lieferant, dem die Aktivität zugewiesen ist', limit_choices_to={'adressen_type': 'LIEFERANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivitaeten_als_lieferant', to='core.adresse', verbose_name='Zugewiesen an (Extern)')),
                ('assigned_user', models.ForeignKey(blank=True, help_text='Interner Benutzer, dem die Aktivität zugewiesen ist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivitaeten', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an (Intern)')),
                ('kunde', models.ForeignKey(blank=True, limit_choices_to={'adressen_type': 'KUNDE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktivitaeten', to='core.adresse', verbose_name='Kunde')),
                ('mietobjekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktivitaeten', to='vermietung.mietobjekt', verbose_name='Mietobjekt')),
                ('vertrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktivitaeten', to='vermietung.vertrag', verbose_name='Vertrag')),
            ],
            options={
                'verbose_name': 'Aktivität',
                'verbose_name_plural': 'Aktivitäten',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='vermietung__status_2bf1e0_idx'), models.Index(fields=['faellig_am'], name='vermietung__faellig_5f81a7_idx'), models.Index(fields=['assigned_user'], name='vermietung__assigne_60f028_idx'), models.Index(fields=['assigned_supplier'], name='vermietung__assigne_d320f3_idx')],
            },
        ),
    ]
