# Generated by Django 5.2.9 on 2025-12-26 21:11

from django.db import migrations


def migrate_vertrag_mietobjekt_to_vertragsobjekt(apps, schema_editor):
    """
    Migrate existing Vertrag.mietobjekt foreign key to VertragsObjekt.
    For each Vertrag that has a mietobjekt, create a VertragsObjekt entry.
    """
    Vertrag = apps.get_model('vermietung', 'Vertrag')
    VertragsObjekt = apps.get_model('vermietung', 'VertragsObjekt')
    
    # Find all vertraege with a mietobjekt set
    vertraege_with_mietobjekt = Vertrag.objects.filter(mietobjekt__isnull=False)
    
    # Create VertragsObjekt entries
    vertragsobjekte_to_create = []
    for vertrag in vertraege_with_mietobjekt:
        vertragsobjekte_to_create.append(
            VertragsObjekt(
                vertrag=vertrag,
                mietobjekt=vertrag.mietobjekt
            )
        )
    
    # Bulk create for efficiency
    if vertragsobjekte_to_create:
        VertragsObjekt.objects.bulk_create(vertragsobjekte_to_create)
        print(f"Migrated {len(vertragsobjekte_to_create)} Vertrag-Mietobjekt relationships to VertragsObjekt.")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: For each Vertrag, set mietobjekt to the first VertragsObjekt's mietobjekt.
    This is a best-effort reverse - if a Vertrag has multiple VertragsObjekte, only the first is preserved.
    """
    Vertrag = apps.get_model('vermietung', 'Vertrag')
    VertragsObjekt = apps.get_model('vermietung', 'VertragsObjekt')
    
    # For each vertrag with vertragsobjekte, set the legacy mietobjekt field
    for vertragsobjekt in VertragsObjekt.objects.select_related('vertrag', 'mietobjekt').order_by('vertrag_id', 'created_at'):
        vertrag = vertragsobjekt.vertrag
        if not vertrag.mietobjekt_id:  # Only set if not already set
            vertrag.mietobjekt = vertragsobjekt.mietobjekt
            vertrag.save(update_fields=['mietobjekt'])
    
    # Delete all VertragsObjekt entries
    VertragsObjekt.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0009_add_vertragsobjekt'),
    ]

    operations = [
        migrations.RunPython(
            migrate_vertrag_mietobjekt_to_vertragsobjekt,
            reverse_migration
        ),
    ]
