# Generated by Django 5.2.9 on 2025-12-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0009_aktivitaet'),
        ('vermietung', '0010_migrate_vertrag_mietobjekt_to_vertragsobjekt'),
    ]

    operations = [
    ]
