# Generated by Django 5.2.9 on 2025-12-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0012_add_vertragsobjekt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mietobjekt',
            name='verfuegbare_einheiten',
            field=models.IntegerField(default=1, help_text='Anzahl der verfügbaren Einheiten (für mehrfach vermietbare Objekte)', verbose_name='Verfügbare Einheiten'),
        ),
        migrations.AddField(
            model_name='mietobjekt',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Volumen in m³ (wird aus H×B×T berechnet, kann überschrieben werden)', max_digits=10, null=True, verbose_name='Volumen (m³)'),
        ),
    ]
