# Generated by Django 5.2.9 on 2025-12-30 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mandant'),
        ('vermietung', '0013_add_units_and_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='mietobjekt',
            name='mandant',
            field=models.ForeignKey(blank=True, help_text='Zugeordneter Mandant für dieses Mietobjekt', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mandant', verbose_name='Mandant'),
        ),
        migrations.AddField(
            model_name='vertrag',
            name='mandant',
            field=models.ForeignKey(blank=True, help_text='Zugeordneter Mandant für diesen Vertrag', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mandant', verbose_name='Mandant'),
        ),
    ]
