# Generated by Django 5.2.9 on 2025-12-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0013_add_units_and_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertrag',
            name='umsatzsteuer_satz',
            field=models.CharField(choices=[('0', '0% Umsatzsteuer (steuerfrei)'), ('7', '7% Umsatzsteuer (Beherbergung)'), ('19', '19% Umsatzsteuer (Gewerbe)')], default='19', help_text='Umsatzsteuersatz für diesen Vertrag', max_length=2, verbose_name='Umsatzsteuer'),
        ),
    ]
