# Generated by Django 5.2.9 on 2025-12-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0014_add_mandant_to_mietobjekt_and_vertrag'),
        ('vermietung', '0014_add_umsatzsteuer_field'),
    ]

    operations = [
    ]
