# Generated by Django 5.2.9 on 2025-12-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0015_merge_20251230_2116'),
        ('vermietung', '0015_merge_20251230_2225'),
    ]

    operations = [
    ]
