# Generated by Django 5.2.9 on 2026-01-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0016_merge_20251230_2246'),
        ('vermietung', '0016_merge_20260102_0938'),
    ]

    operations = [
    ]
