# Generated by Django 5.2.10 on 2026-01-20 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0016_merge_20260102_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaehler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('STROM', 'Strom'), ('GAS', 'Gas'), ('WASSER', 'Wasser'), ('HEIZUNG', 'Heizung'), ('KUEHLUNG', 'Kühlung')], help_text='Typ des Zählers (Strom, Gas, Wasser, Heizung, Kühlung)', max_length=20, verbose_name='Zählertyp')),
                ('bezeichnung', models.CharField(help_text="Beschreibende Bezeichnung des Zählers (z.B. 'Wohnung EG links', 'Garage 1–3')", max_length=255, verbose_name='Bezeichnung')),
                ('einheit', models.CharField(help_text='Maßeinheit (kWh, m³, etc.)', max_length=20, verbose_name='Einheit')),
                ('mietobjekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaehler', to='vermietung.mietobjekt', verbose_name='Mietobjekt')),
                ('parent', models.ForeignKey(blank=True, help_text='Optional: Hauptzähler, wenn dieser Zähler ein Zwischenzähler ist', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_zaehler', to='vermietung.zaehler', verbose_name='Übergeordneter Zähler')),
            ],
            options={
                'verbose_name': 'Zähler',
                'verbose_name_plural': 'Zähler',
                'ordering': ['mietobjekt', 'typ', 'bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Zaehlerstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(help_text='Datum der Ablesung', verbose_name='Datum')),
                ('wert', models.DecimalField(decimal_places=3, help_text='Wert des Zählerstands (z.B. kWh, m³)', max_digits=12, verbose_name='Zählerstand')),
                ('zaehler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staende', to='vermietung.zaehler', verbose_name='Zähler')),
            ],
            options={
                'verbose_name': 'Zählerstand',
                'verbose_name_plural': 'Zählerstände',
                'ordering': ['-datum'],
                'unique_together': {('zaehler', 'datum')},
            },
        ),
    ]
