# Generated by Django 5.2.10 on 2026-01-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0017_merge_20260120_2236'),
        ('vermietung', '0017_zaehler_zaehlerstand'),
    ]

    operations = [
    ]
