# Generated by Django 5.2.10 on 2026-01-22 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0018_merge_20260122_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='mietobjekt',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Übergeordnetes Mietobjekt (z.B. Gebäude für eine Wohnung)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='vermietung.mietobjekt', verbose_name='Übergeordnetes Mietobjekt'),
        ),
    ]
