# Generated by Django 5.2.9 on 2026-01-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0018_merge_20260122_2050'),
        ('vermietung', '0019_add_parent_child_hierarchy'),
    ]

    operations = [
    ]
