# Generated by Django 5.2.10 on 2026-01-22 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_vat_to_kostenart'),
        ('vermietung', '0019_add_parent_child_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eingangsrechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belegdatum', models.DateField(verbose_name='Belegdatum')),
                ('faelligkeit', models.DateField(verbose_name='Fälligkeit')),
                ('belegnummer', models.CharField(max_length=100, verbose_name='Belegnummer')),
                ('betreff', models.CharField(max_length=200, verbose_name='Betreff')),
                ('referenznummer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referenznummer')),
                ('leistungszeitraum_von', models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum von')),
                ('leistungszeitraum_bis', models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum bis')),
                ('notizen', models.TextField(blank=True, null=True, verbose_name='Notizen')),
                ('status', models.CharField(choices=[('NEU', 'Neu'), ('PRUEFUNG', 'Prüfung'), ('OFFEN', 'Offen'), ('KLAERUNG', 'Klärung'), ('BEZAHLT', 'Bezahlt')], default='NEU', max_length=20, verbose_name='Status')),
                ('zahlungsdatum', models.DateField(blank=True, null=True, verbose_name='Zahlungsdatum')),
                ('umlagefaehig', models.BooleanField(default=True, verbose_name='Umlagefähig')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('lieferant', models.ForeignKey(limit_choices_to={'adressen_type': 'LIEFERANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='eingangsrechnungen', to='core.adresse', verbose_name='Lieferant')),
                ('mietobjekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eingangsrechnungen', to='vermietung.mietobjekt', verbose_name='Mietobjekt')),
            ],
            options={
                'verbose_name': 'Eingangsrechnung',
                'verbose_name_plural': 'Eingangsrechnungen',
                'ordering': ['-belegdatum', '-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='EingangsrechnungAufteilung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nettobetrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nettobetrag')),
                ('beschreibung', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beschreibung')),
                ('eingangsrechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufteilungen', to='vermietung.eingangsrechnung', verbose_name='Eingangsrechnung')),
                ('kostenart1', models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='aufteilungen_hauptkostenart', to='core.kostenart', verbose_name='Kostenart 1 (Hauptkostenart)')),
                ('kostenart2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aufteilungen_unterkostenart', to='core.kostenart', verbose_name='Kostenart 2 (Unterkostenart)')),
            ],
            options={
                'verbose_name': 'Eingangsrechnungsaufteilung',
                'verbose_name_plural': 'Eingangsrechnungsaufteilungen',
                'ordering': ['id'],
            },
        ),
    ]
