# Generated by Django 5.2.9 on 2026-01-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0020_add_eingangsrechnung_models'),
        ('vermietung', '0020_merge_20260122_2224'),
    ]

    operations = [
    ]
