# Generated by Django 5.2.10 on 2026-01-28 16:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_vat_to_kostenart'),
        ('vermietung', '0021_merge_20260122_2237'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitaet',
            name='ersteller',
            field=models.ForeignKey(help_text='Benutzer, der diese Aktivität erstellt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivitaeten_erstellt', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller'),
        ),
        migrations.AddField(
            model_name='aktivitaet',
            name='intervall_monate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Intervall in Monaten für wiederkehrende Aktivitäten (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Intervall (Monate)'),
        ),
        migrations.AddField(
            model_name='aktivitaet',
            name='ist_serie',
            field=models.BooleanField(default=False, help_text='Ist dies eine wiederkehrende Aktivität?', verbose_name='Serien-Aktivität'),
        ),
        migrations.AddField(
            model_name='aktivitaet',
            name='serien_id',
            field=models.UUIDField(blank=True, help_text='Eindeutige ID zur Gruppierung von Aktivitäten einer Serie', null=True, verbose_name='Serien-ID'),
        ),
        migrations.AddIndex(
            model_name='aktivitaet',
            index=models.Index(fields=['ersteller'], name='vermietung__erstell_6e448c_idx'),
        ),
        migrations.AddIndex(
            model_name='aktivitaet',
            index=models.Index(fields=['ist_serie'], name='vermietung__ist_ser_ffae06_idx'),
        ),
        migrations.AddIndex(
            model_name='aktivitaet',
            index=models.Index(fields=['serien_id'], name='vermietung__serien__ae9181_idx'),
        ),
    ]
