# Generated by Django 5.2.10 on 2026-01-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0022_add_ersteller_and_series_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertrag',
            name='auto_total',
            field=models.BooleanField(default=True, help_text='Wenn aktiviert, wird der Gesamtbetrag aus den Vertragszeilen berechnet. Wenn deaktiviert, kann ein manueller Pauschalpreis eingegeben werden.', verbose_name='Automatische Gesamtberechnung'),
        ),
        migrations.AddField(
            model_name='vertrag',
            name='manual_net_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manueller Netto-Gesamtpreis (Pauschale). Nur relevant wenn automatische Berechnung deaktiviert ist.', max_digits=10, null=True, verbose_name='Manueller Netto-Gesamtpreis'),
        ),
        migrations.AlterField(
            model_name='vertrag',
            name='vertragsnummer',
            field=models.CharField(blank=True, help_text='Vertragsnummer (wird automatisch generiert, wenn leer gelassen)', max_length=10, unique=True, verbose_name='Vertragsnummer'),
        ),
    ]
