# Generated by Django 5.2.9 on 2026-01-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0022_add_ersteller_and_series_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertrag',
            name='vertragsnummer',
            field=models.CharField(blank=True, help_text='Vertragsnummer (wird automatisch generiert, wenn leer gelassen)', max_length=10, unique=True, verbose_name='Vertragsnummer'),
        ),
    ]
