# Generated by Django 5.2.9 on 2026-01-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0023_add_flat_rate_fields'),
        ('vermietung', '0023_alter_vertrag_vertragsnummer'),
    ]

    operations = [
    ]
