# Generated by Django 5.2.10 on 2026-01-31 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_password_reset_mail_template'),
        ('vermietung', '0023_add_flat_rate_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitaet',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die Erinnerungs-E-Mail gesendet wurde', null=True, verbose_name='Erinnerung gesendet am'),
        ),
        migrations.AddIndex(
            model_name='aktivitaet',
            index=models.Index(fields=['reminder_sent_at'], name='vermietung__reminde_62ca2c_idx'),
        ),
    ]
