# Generated by Django 5.2.9 on 2026-01-31 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0024_add_reminder_sent_at_to_aktivitaet'),
        ('vermietung', '0024_merge_20260131_0912'),
    ]

    operations = [
    ]
