# Generated by Django 5.2.10 on 2026-01-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0025_merge_20260131_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='mietobjekt',
            name='is_mietobjekt',
            field=models.BooleanField(default=True, help_text='Kennzeichnet, ob es sich um ein Mietobjekt handelt', verbose_name='Mietobjekt'),
        ),
    ]
