# Generated by Django 5.2.10 on 2026-01-31 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0026_add_is_mietobjekt_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='eingangsrechnung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='vermietung.eingangsrechnung', verbose_name='Eingangsrechnung'),
        ),
    ]
