# Generated by Django 5.2.10 on 2026-02-01 17:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0027_add_eingangsrechnung_to_dokument'),
    ]

    operations = [
        migrations.AddField(
            model_name='mietobjekt',
            name='price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mietpreis pro Quadratmeter (€/m²)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preis pro m²'),
        ),
    ]
