# Generated by Django 5.2.10 on 2026-02-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0027_add_eingangsrechnung_to_dokument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietobjekt',
            name='mietpreis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
