# Generated by Django 5.2.10 on 2026-02-01 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reportdocument'),
        ('vermietung', '0028_mietobjekt_price_per_sqm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AktivitaetsBereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name der Kategorie/des Bereichs', max_length=100, unique=True, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, help_text='Optionale Beschreibung der Kategorie', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Aktivitäts-Bereich',
                'verbose_name_plural': 'Aktivitäts-Bereiche',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='aktivitaet',
            name='bereich',
            field=models.ForeignKey(blank=True, help_text='Optional: Kategorie/Bereich dieser Aktivität', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivitaeten', to='vermietung.aktivitaetsbereich', verbose_name='Bereich'),
        ),
        migrations.AddIndex(
            model_name='aktivitaet',
            index=models.Index(fields=['bereich'], name='vermietung__bereich_967d4c_idx'),
        ),
    ]
