# Generated by Django 5.2.10 on 2026-02-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0029_add_aktivitaetsbereich_and_optional_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitaet',
            name='ersteller',
            field=models.ForeignKey(blank=True, help_text='Benutzer, der diese Aktivität erstellt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivitaeten_erstellt', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller'),
        ),
    ]
