# Generated by Django 5.2.10 on 2026-02-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0029_make_mietpreis_optional'),
        ('vermietung', '0030_make_ersteller_optional'),
    ]

    operations = [
    ]
