# Generated by Django 5.2.10 on 2026-02-01 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0031_merge_20260201_1953'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitaet',
            name='cc_users',
            field=models.ManyToManyField(blank=True, help_text='Benutzer, die zur Kontrolle/Information über diese Aktivität benachrichtigt werden', related_name='aktivitaeten_cc', to=settings.AUTH_USER_MODEL, verbose_name='Zur Kontrolle informieren'),
        ),
    ]
