# Generated by Django 5.2.11 on 2026-02-09 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_handelsregister_to_mandant'),
        ('vermietung', '0032_add_cc_users_to_aktivitaet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitaet',
            name='privat',
            field=models.BooleanField(default=False, help_text='Private Aktivitäten sind nur für den Ersteller und Verantwortlichen sichtbar', verbose_name='Privat'),
        ),
        migrations.AddIndex(
            model_name='aktivitaet',
            index=models.Index(fields=['privat'], name='vermietung__privat_5584bd_idx'),
        ),
    ]
