# Generated by Django 5.2.11 on 2026-02-13 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0033_add_privat_field_to_aktivitaet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AktivitaetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='Der ursprüngliche Dateiname beim Upload', max_length=255, verbose_name='Originaler Dateiname')),
                ('storage_path', models.CharField(help_text='Relativer Pfad zur Datei', max_length=500, verbose_name='Speicherpfad')),
                ('file_size', models.IntegerField(help_text='Dateigröße in Bytes', verbose_name='Dateigröße')),
                ('mime_type', models.CharField(help_text='MIME-Type der Datei', max_length=100, verbose_name='MIME-Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt des Uploads', verbose_name='Hochgeladen am')),
                ('aktivitaet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vermietung.aktivitaet', verbose_name='Aktivität')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Benutzer, der die Datei hochgeladen hat', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Aktivitäts-Anhang',
                'verbose_name_plural': 'Aktivitäts-Anhänge',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
