# Generated by Django 5.2.11 on 2026-02-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0034_aktivitaetattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertrag',
            name='bemerkung',
            field=models.TextField(blank=True, help_text='Freitextfeld für Hinweise und Bemerkungen zum Mietvertrag', null=True, verbose_name='Bemerkung'),
        ),
    ]
