# Generated by Django 5.2.11 on 2026-02-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0035_add_vertrag_bemerkung'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertrag',
            name='stellplatzbetrag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Zusätzlicher Betrag für Stellplätze in EUR (optional)', max_digits=10, null=True, verbose_name='Stellplatzbetrag'),
        ),
    ]
