# Generated by Django 5.2.11 on 2026-03-01 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lieferantenwesen', '0004_migrate_eingangsrechnung_data'),
        ('vermietung', '0036_add_stellplatzbetrag_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='invoice_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente_vermietung', to='lieferantenwesen.invoicein', verbose_name='Eingangsrechnung (global)'),
        ),
    ]
