# Generated by Django 5.2.11 on 2026-03-01 09:59

from django.db import migrations


def migrate_dokument_references(apps, schema_editor):
    """
    Migrate Dokument references from Eingangsrechnung to InvoiceIn.

    We need to match documents based on the invoice data since we don't have
    a direct ID mapping. We'll match by:
    - Invoice number (belegnummer / invoice_no)
    - Invoice date (belegdatum / invoice_date)
    - Supplier (lieferant / supplier)
    """
    Dokument = apps.get_model('vermietung', 'Dokument')
    Eingangsrechnung = apps.get_model('vermietung', 'Eingangsrechnung')
    InvoiceIn = apps.get_model('lieferantenwesen', 'InvoiceIn')

    updated_count = 0
    not_found_count = 0

    # Process each document linked to an Eingangsrechnung
    for dokument in Dokument.objects.filter(eingangsrechnung__isnull=False).select_related('eingangsrechnung'):
        old_invoice = dokument.eingangsrechnung

        # Find matching InvoiceIn by matching fields
        try:
            new_invoice = InvoiceIn.objects.get(
                invoice_no=old_invoice.belegnummer,
                invoice_date=old_invoice.belegdatum,
                supplier=old_invoice.lieferant,
                rental_object=old_invoice.mietobjekt,
            )

            # Update the document to point to the new invoice
            dokument.invoice_in = new_invoice
            dokument.eingangsrechnung = None  # Clear old reference
            dokument.save(update_fields=['invoice_in', 'eingangsrechnung'])
            updated_count += 1

        except InvoiceIn.DoesNotExist:
            print(f"Warning: Could not find matching InvoiceIn for Eingangsrechnung #{old_invoice.id} "
                  f"(Belegnummer: {old_invoice.belegnummer})")
            not_found_count += 1
        except InvoiceIn.MultipleObjectsReturned:
            print(f"Warning: Multiple InvoiceIn records found for Eingangsrechnung #{old_invoice.id} "
                  f"(Belegnummer: {old_invoice.belegnummer}). Using first match.")
            new_invoice = InvoiceIn.objects.filter(
                invoice_no=old_invoice.belegnummer,
                invoice_date=old_invoice.belegdatum,
                supplier=old_invoice.lieferant,
                rental_object=old_invoice.mietobjekt,
            ).first()
            dokument.invoice_in = new_invoice
            dokument.eingangsrechnung = None
            dokument.save(update_fields=['invoice_in', 'eingangsrechnung'])
            updated_count += 1

    print(f"\nDokument migration completed:")
    print(f"  - Documents updated: {updated_count}")
    print(f"  - Documents not found: {not_found_count}")


def reverse_dokument_migration(apps, schema_editor):
    """
    Reverse the document migration by setting eingangsrechnung back.
    """
    Dokument = apps.get_model('vermietung', 'Dokument')
    Eingangsrechnung = apps.get_model('vermietung', 'Eingangsrechnung')
    InvoiceIn = apps.get_model('lieferantenwesen', 'InvoiceIn')

    updated_count = 0
    not_found_count = 0

    # Process documents linked to InvoiceIn with rental_object
    for dokument in Dokument.objects.filter(invoice_in__isnull=False, invoice_in__rental_object__isnull=False).select_related('invoice_in'):
        new_invoice = dokument.invoice_in

        # Find matching Eingangsrechnung
        try:
            old_invoice = Eingangsrechnung.objects.get(
                belegnummer=new_invoice.invoice_no,
                belegdatum=new_invoice.invoice_date,
                lieferant=new_invoice.supplier,
                mietobjekt=new_invoice.rental_object,
            )

            dokument.eingangsrechnung = old_invoice
            dokument.invoice_in = None
            dokument.save(update_fields=['eingangsrechnung', 'invoice_in'])
            updated_count += 1

        except Eingangsrechnung.DoesNotExist:
            print(f"Warning: Could not find matching Eingangsrechnung for InvoiceIn #{new_invoice.id}")
            not_found_count += 1

    print(f"\nReverse Dokument migration completed:")
    print(f"  - Documents updated: {updated_count}")
    print(f"  - Documents not found: {not_found_count}")


class Migration(migrations.Migration):

    dependencies = [
        ('vermietung', '0037_add_invoice_in_fk_to_dokument'),
        ('lieferantenwesen', '0004_migrate_eingangsrechnung_data'),
    ]

    operations = [
        migrations.RunPython(
            migrate_dokument_references,
            reverse_dokument_migration,
        ),
    ]
