# Generated by Django 5.2.17 on 2026-08-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auftragsverwaltung",
            "0026_remove_numberrange_numberrange_document_requires_doctype_and_more",
        ),
        ("vermietung", "0038_migrate_dokument_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokument",
            name="salesdocument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dokumente",
                to="auftragsverwaltung.salesdocument",
                verbose_name="Verkaufsbeleg",
            ),
        ),
    ]
